[package]
edition = "2021"
name = "sneturfahi"
version = "0.1.0"

[dependencies]
log = "0.4"
macros = { path = "macros" }
nom = "7"
thiserror = "1"

[dev-dependencies]
atty = "0.2"
simplelog = "0.12"

[features]
type-alias-impl-trait = []
