use std::fmt::{Display, Formatter, Result};

impl Display for super::Selmaho {
	fn fmt(&self, f: &mut Formatter<'_>) -> Result {
		f.write_str(self.as_repr())
	}
}

impl super::Selmaho {
	/// Get the string representation of the selmaho.
	///
	/// For actual selmaho, this is the capital representation, which is the Lojban convention.
	///
	/// ```rust
	/// # use sneturfahi::lex::selmaho::Selmaho;
	/// assert_eq!(Selmaho::Beho.as_repr(), "BEhO");
	/// ```
	///
	/// For non-cmavo selmaho, this is the lowercase name of that construct.
	///
	/// ```rust
	/// # use sneturfahi::lex::selmaho::Selmaho;
	/// assert_eq!(Selmaho::Gismu.as_repr(), "gismu");
	/// ```
	///
	/// For technical selmaho, this is a description in parenthesis.
	///
	/// ```rust
	/// # use sneturfahi::lex::selmaho::Selmaho;
	/// assert_eq!(Selmaho::ZoiDelimiter.as_repr(), "(zoi delimiter)");
	/// ```
	#[allow(clippy::too_many_lines)] // giant match block
	#[must_use]
	pub fn as_repr(self) -> &'static str {
		match self {
			// regular cmavo
			Self::A => "A",
			Self::Bai => "BAI",
			Self::Bahe => "BAhE",
			Self::Be => "BE",
			Self::Bei => "BEI",
			Self::Beho => "BEhO",
			Self::Bihe => "BIhE",
			Self::Bihi => "BIhI",
			Self::Bo => "BO",
			Self::Boi => "BOI",
			Self::Bu => "BU",
			Self::By => "BY",
			Self::Cai => "CAI",
			Self::Caha => "CAhA",
			Self::Cei => "CEI",
			Self::Cehe => "CEhE",
			Self::Co => "CO",
			Self::Coi => "COI",
			Self::Cu => "CU",
			Self::Cuhe => "CUhE",
			Self::Daho => "DAhO",
			Self::Doi => "DOI",
			Self::Dohu => "DOhU",
			Self::Fa => "FA",
			Self::Faha => "FAhA",
			Self::Faho => "FAhO",
			Self::Fehe => "FEhE",
			Self::Fehu => "FEhU",
			Self::Fiho => "FIhO",
			Self::Foi => "FOI",
			Self::Fuha => "FUhA",
			Self::Fuhe => "FUhE",
			Self::Fuho => "FUhO",
			Self::Ga => "GA",
			Self::Gaho => "GAhO",
			Self::Gehu => "GEhU",
			Self::Gi => "GI",
			Self::Giha => "GIhA",
			Self::Goi => "GOI",
			Self::Goha => "GOhA",
			Self::Guha => "GUhA",
			Self::I => "I",
			Self::Ja => "JA",
			Self::Jai => "JAI",
			Self::Joi => "JOI",
			Self::Johi => "JOhI",
			Self::Ke => "KE",
			Self::Kei => "KEI",
			Self::Kehe => "KEhE",
			Self::Ki => "KI",
			Self::Koha => "KOhA",
			Self::Ku => "KU",
			Self::Kuhe => "KUhE",
			Self::Kuho => "KUhO",
			Self::La => "LA",
			Self::Lau => "LAU",
			Self::Lahe => "LAhE",
			Self::Le => "LE",
			Self::Lehu => "LEhU",
			Self::Li => "LI",
			Self::Lihu => "LIhU",
			Self::Loho => "LOhO",
			Self::Lohu => "LOhU",
			Self::Lu => "LU",
			Self::Luhu => "LUhU",
			Self::Mai => "MAI",
			Self::Maho => "MAhO",
			Self::Me => "ME",
			Self::Mehu => "MEhU",
			Self::Moi => "MOI",
			Self::Mohe => "MOhE",
			Self::Mohi => "MOhI",
			Self::Na => "NA",
			Self::Nai => "NAI",
			Self::Nahe => "NAhE",
			Self::Nahu => "NAhU",
			Self::Nihe => "NIhE",
			Self::Niho => "NIhO",
			Self::Noi => "NOI",
			Self::Nu => "NU",
			Self::Nuha => "NUhA",
			Self::Nuhi => "NUhI",
			Self::Nuhu => "NUhU",
			Self::Pa => "PA",
			Self::Pehe => "PEhE",
			Self::Peho => "PEhO",
			Self::Pu => "PU",
			Self::Raho => "RAhO",
			Self::Roi => "ROI",
			Self::Sa => "SA",
			Self::Se => "SE",
			Self::Sei => "SEI",
			Self::Sehu => "SEhU",
			Self::Si => "SI",
			Self::Soi => "SOI",
			Self::Su => "SU",
			Self::Tahe => "TAhE",
			Self::Tei => "TEI",
			Self::Tehu => "TEhU",
			Self::To => "TO",
			Self::Toi => "TOI",
			Self::Tuhe => "TUhE",
			Self::Tuhu => "TUhU",
			Self::Ui => "UI",
			Self::Va => "VA",
			Self::Vau => "VAU",
			Self::Vei => "VEI",
			Self::Veha => "VEhA",
			Self::Veho => "VEhO",
			Self::Viha => "VIhA",
			Self::Vuho => "VUhO",
			Self::Vuhu => "VUhU",
			Self::Xi => "XI",
			Self::Y => "Y",
			Self::Zaho => "ZAhO",
			Self::Zei => "ZEI",
			Self::Zeha => "ZEhA",
			Self::Zi => "ZI",
			Self::Zihe => "ZIhE",
			Self::Zo => "ZO",
			Self::Zoi => "ZOI",
			Self::Zohu => "ZOhU",

			// experimental selmaho
			Self::Bahei => "BAhEI",
			Self::Beihe => "BEIhE",
			Self::Boihoi => "BOIhOI",
			Self::Boihohu => "BOIhOhU",
			Self::Cahei => "CAhEI",
			Self::Ceheihoi => "CEhEIhOI",
			Self::Cohai => "COhAI",
			Self::Cohehohe => "COhEhOhE",
			Self::Cohuho => "COhUhO",
			Self::Cuhau => "CUhAU",
			Self::Dauho => "DAUhO",
			Self::Dehai => "DEhAI",
			Self::Dehau => "DEhAU",
			Self::Dohoi => "DOhOI",
			Self::Fauha => "FAUhA",
			Self::Fahoho => "FAhOhO",
			Self::Fihoi => "FIhOI",
			Self::Foihe => "FOIhE",
			Self::Gahuhau => "GAhUhAU",
			Self::Gehuhi => "GEhUhI",
			Self::Gihei => "GIhEI",
			Self::Gihoi => "GIhOI",
			Self::Gohoi => "GOhOI",
			Self::Ihau => "IhAU",
			Self::Jaiha => "JAIhA",
			Self::Jaihi => "JAIhI",
			Self::Jauhu => "JAUhU",
			Self::Jahoi => "JAhOI",
			Self::Jihoi => "JIhOI",
			Self::Joihi => "JOIhI",
			Self::Johe => "JOhE",
			Self::Juhau => "JUhAU",
			Self::Juhei => "JUhEI",
			Self::Juhuhi => "JUhUhI",
			Self::Kauhai => "KAUhAI",
			Self::Kauhu => "KAUhU",
			Self::Keihau => "KEIhAU",
			Self::Keihi => "KEIhI",
			Self::Kehai => "KEhAI",
			Self::Kehei => "KEhEI",
			Self::Keheiha => "KEhEIhA",
			Self::Kehehau => "KEhEhAU",
			Self::Kehehu => "KEhEhU",
			Self::Kehuhi => "KEhUhI",
			Self::Kuhau => "KUhAU",
			Self::Kuhei => "KUhEI",
			Self::Kuhoihu => "KUhOIhU",
			Self::Kyhoi => "KYhOI",
			Self::Lehai => "LEhAI",
			Self::Lihau => "LIhAU",
			Self::Lihei => "LIhEI",
			Self::Lohai => "LOhAI",
			Self::Lohoi => "LOhOI",
			Self::Luhei => "LUhEI",
			Self::Mauhau => "MAUhAU",
			Self::Mauhe => "MAUhE",
			Self::Mauho => "MAUhO",
			Self::Meihe => "MEIhE",
			Self::Meiho => "MEIhO",
			Self::Mehoi => "MEhOI",
			Self::Muhoi => "MUhOI",
			Self::Muhohu => "MUhOhU",
			Self::Neihai => "NEIhAI",
			Self::Noiha => "NOIhA",
			Self::Noihau => "NOIhAU",
			Self::Noihahu => "NOIhAhU",
			Self::Noihi => "NOIhI",
			Self::Nohoi => "NOhOI",
			Self::Rauho => "RAUhO",
			Self::Rehaihe => "REhAIhE",
			Self::Sauhu => "SAUhU",
			Self::Sahau => "SAhAU",
			Self::Sahoi => "SAhOI",
			Self::Seihau => "SEIhAU",
			Self::Seiho => "SEIhO",
			Self::Sehehi => "SEhEhI",
			Self::Sehoihoi => "SEhOIhOI",
			Self::Sihihei => "SIhIhEI",
			Self::Sihihoi => "SIhIhOI",
			Self::Sihoi => "SIhOI",
			Self::Soihi => "SOIhI",
			Self::Sohehai => "SOhEhAI",
			Self::Sohoi => "SOhOI",
			Self::Taihu => "TAIhU",
			Self::Tauho => "TAUhO",
			Self::Tahoi => "TAhOI",
			Self::Tahuhi => "TAhUhI",
			Self::Teihu => "TEIhU",
			Self::Tehoihoi => "TEhOIhOI",
			Self::Toihe => "TOIhE",
			Self::Toiho => "TOIhO",
			Self::Vauhehoi => "VAUhEhOI",
			Self::Vauhohoi => "VAUhOhOI",
			Self::Vuhoi => "VUhOI",
			Self::Vyhy => "VYhY",
			Self::Xauhe => "XAUhE",
			Self::Xauheho => "XAUhEhO",
			Self::Xauho => "XAUhO",
			Self::Xauhoi => "XAUhOI",
			Self::Xauhoho => "XAUhOhO",
			Self::Xahoihahoiha => "XAhOIhAhOIhA",
			Self::Xehau => "XEhAU",
			Self::Xoi => "XOI",
			Self::Xoha => "XOhA",
			Self::Xohehohe => "XOhEhOhE",
			Self::Xohi => "XOhI",
			Self::Xuhau => "XUhAU",
			Self::Yhi => "YhI",
			Self::Zaihai => "ZAIhAI",
			Self::Zaihu => "ZAIhU",
			Self::Zauhehu => "ZAUhEhU",
			Self::Zeihei => "ZEIhEI",
			Self::Zeihoi => "ZEIhOI",
			Self::Ziheha => "ZIhEhA",
			Self::Zihehau => "ZIhEhAU",
			Self::Zihoi => "ZIhOI",
			Self::Zoihai => "ZOIhAI",
			Self::Zoihohe => "ZOIhOhE",
			Self::Zohau => "ZOhAU",
			Self::Zohehu => "ZOhEhU",
			Self::Zohiho => "ZOhIhO",
			Self::Zohoi => "ZOhOI",

			// non-cmavo selmaho
			Self::Gismu => "gismu",
			Self::Fuhivla => "fuhivla",
			Self::Lujvo => "lujvo",
			Self::Cmevla => "cmevla",

			// technical selmaho
			Self::UnknownCmavo => "(unknown cmavo)",
			Self::AnyText => "(any text)",
			Self::ZoiDelimiter => "(zoi delimiter)",
		}
	}
}
