macro_rules! assert_parse {
	($($sentence:tt),* $(,)?) => {
		$(
			macros::make_assert_parse_test!($sentence);
		)*
	};
}

assert_parse![
	// 5.1
	"do mamta mi",
	"do patfu mi",
	"ta bloti",
	"ta brablo",
	"ta blotrskunri",
	// 5.2
	"tu pelnimre tricu",
	"la djan barda nanla",
	"mi sutra bajra",
	"mi sutra",
	"ta klama jubme",
	"do barda prenu",
	"do cmalu prenu",
	// 5.3
	"ta cmalu nixli bo ckule",
	"ta cmalu bo nixli ckule",
	"ta cmalu nixli ckule",
	"ta klama bo jubme",
	// 5.4
	"do mutce bo barda gerku bo kavbu",
	"ta melbi cmalu nixli ckule",
	"ta melbi cmalu nixli bo ckule",
	"ta melbi cmalu bo nixli ckule",
	"ta melbi cmalu bo nixli bo ckule",
	"ta cmalu bo nixli bo ckule",
	// 5.5
	"ta ke melbi cmalu ke'e nixli ckule",
	"ta ke ke melbi cmalu ke'e nixli ke'e ckule",
	"ta ke ke ke melbi cmalu ke'e nixli ke'e ckule ke'e",
	"ta melbi ke cmalu nixli ke'e ckule",
	"ta melbi cmalu ke nixli ckule",
	"ta melbi cmalu ke nixli ckule ke'e",
	"ta melbi ke cmalu nixli ckule",
	"ta melbi ke cmalu nixli ckule ke'e",
	"ta melbi ke cmalu ke nixli ckule",
	"ta melbi ke cmalu ke nixli ckule ke'e",
	"ta melbi ke cmalu ke nixli ckule ke'e ke'e",
	"ta melbi ke cmalu nixli bo ckule",
	"ta melbi ke cmalu nixli bo ckule ke'e",
	// 5.6
	"barda xunre gerku",
	"barda xunre bo gerku",
	"barda je xunre gerku",
	"xunre je barda gerku",
	"barda je pelxu bo xunre gerku",
	"barda je ke pelxu xunre ke'e gerku",
	"barda je pelxu xunre gerku",
	"ta blanu je zdani",
	"ta melbi je nixli ckule",
	"ta ke melbi ckule ke'e je ke nixli ckule",
	"ta ke melbi ckule ke'e je ke nixli ckule ke'e",
	"le bajra cu jinga ja te jinga",
	"blanu naja lenku skapi",
	"xamgu jo tordu nuntavla",
	"vajni ju pluka nuntavla",
	"ricfu je blanu jabo crinu",
	"ricfu je blanu jabo crino bo blanu",
	"ricfu je ke blanu ja crino",
	"ricfu je ke blanu ja crino ke'e",
	"ti blanu joi xunre bolci",
	"ti blanu xunre bolci",
	"ti blanu je xunre bolci",
	"gu'e barda gi xunre gerku",
	"gu'e barda je xunre gi gerku ja mlatu",
	// 5.7
	"ti xamgu zdani",
	"ti xamgu be do bei mi zdani",
	"ti xamgu be do bei mi be'o zdani",
	"ti cmalu be le ka se canlu bei lo'e ckule be'o nixli be le nanca be li mu be'o bei lo merku be'o bo ckule la bryklyn loi pemci le mela nu,IORK prenu le jecta",
	"mi klama be le zarci bei le zdani",
	"mi klama be le zarci bei le zdani be'o",
	"mi klama le zarci le zdani",
	"melbi je cmalu nixli bo ckule",
	"ti xamgu be fi mi bei fe do zdani",
	"ti xamgu be fi mi bei fe do be'o zdani",
	"ti xamgu be fi mi zdani",
	"ti xamgu be fi mi be'o zdani",
	"ta blanu be ga'a mi zdani",
	"ta blanu be ga'a mi be'o zdani",
	"ta blanu zdani ga'a mi",
	"le xamgu be do noi barda cu zdani",
	"le xamgu be do be'o noi barda cu zdani",
	"le xamgu be le ctuca be'o zdani",
	"le xamgu be le ctuca ku be'o zdani",
	// 5.8
	"ta blanu zdani",
	"ta zdani co blanu",
	"mi klama be le zarci bei le zdani be'o troci",
	"mi troci co klama le zarci le zdani",
	"ta nixli ckule co cmalu",
	"ta nixli bo ckule co cmalu",
	"ta cmalu ke nixli ckule co melbi",
	"ta cmalu ke nixli ckule ke'e co melbi",
	"ckule co melbi nixli",
	"ke melbi nixli ke'e ckule",
	"ckule co nixli co cmalu",
	"ke ke cmalu ke'e nixli ke'e ckule",
	"cmalu nixli ckule",
	"mi klama co sutra",
	"mi klama be le zarci be'o co sutra",
	// 5.9
	"la djan klama le zarci",
	"la djan go'i troci",
	"la djan klama be le zarci be'o traci",
	"li vo nu'a su'i li re li re",
	"mi jimpe tu'a loi nu'a su'i nabmi",
	"la prim palvr pamoi cusku",
	// corrected to remove glides
	"la anis joi la asun bruna remei",
	"ti nu zdile kei kumfa",
	"ti zdile kumfa",
	// 5.10
	"le ci nolraitru",
	"la BALtazar cu me le ci nolraitru",
	"do du la djan",
	"do me la djan",
	"ta me lai kraislr karce",
	"ta me lai kraislr me'u karce",
	"re me le ci nolraitru e la djan cu blabi",
	"re me le ci nolraitru e la djan me'u cu blabi",
	"re me le ci nolraitru me'u e la djan cu blabi",
	"ta me la'e le se cusku be do me'u cukta",
	"le me le ci noltraitru me'u nunsalci",
	"le me le ci noltraitru ku me'u nunsalci",
	// 5.11
	// duplicate: "mi prami do",
	"do se prami mi",
	"la alis cu cadzu klama le zarci",
	"le zarci cu se ke cadzu klama ke'e la alis",
	"le zarci cu se cadzu klama la alis",
	"le zarci cu cadzu se klama la alis",
	"la djan cu cadzu se klama la alis",
	// 5.12
	"la alis cu na'e ke cadzu klama le zarci",
	"la alis cu na'e ke cadzu klama ke'e le zarci",
	"la alis cu na'e cadzu klama le zarci",
	"la djonz cu na'e pamoi cusku",
	"mi na'e sutra bo cadzu be fi le birka be'o klama le zarci",
	"mi na'e ke sutra cadzu be fi le birka ke'e klama le zarci",
	"mi na'e ke sutra cadzu be fi le birka be'o ke'e klama le zarci",
	"mi sutra bo cadzu be fi le birka be'o je masno klama le zarci",
	"mi ke sutra cadzu be fi le birka ke'e je masno klama le zarci",
	"mi ke sutra cadzu be fi le birka be'o ke'e je masno klama le zarci",
	"mi na'e ke sutra bo cadzu be fi le birka be'o je masno klama le zarci",
	"mi na'e ke sutra bo cadzu be fi le birka be'o je masno klama ke'e le zarci",
	"mi na'e ke sutra bo cadzu be fi le birka je masno klama le zarci",
	"mi na'e ke sutra bo cadzu be fi le birka je masno klama be'o le zarci",
	"mi na'e ke sutra bo cadzu be fi le birka je masno klama ke'e le zarci",
	"mi na'e ke sutra bo cadzu be fi le birka je masno klama be'o ke'e le zarci",
	// 5.13
	"mi pu klama le zarci",
	"la djonz na pamoi cusku",
	"mi na pu klama le zarci",
	"mi na na klama le zarci",
	"mi na pu na ca klama le zarci",
	// 6.1
	"mi klama le zarci",
	"e'osai ko sarji la lojban",
	"mi cusku lu e'osai li'u le tcidu",
	"ti mitre li ci",
	// 6.2
	"le zarci",
	"le zarci cu barda",
	"le nanmu cu ninmu",
	"lo zarci",
	"lo nanmu cu ninmu",
	"la cribe pu finti le lisri",
	"la stace pu citka lo cirla",
	"lo cribe pu finti le lisri",
	"le remna pu finti le lisri",
	"lo remna pu finti le lisri",
	// 6.3
	"le prenu cu bevri le pipno",
	"lei prenu cu bevri le pipno",
	"loi cinfo cu xabju le fi'ortu'a",
	"loi glipre cu xabju le fi'ortu'a",
	"loi matne cu ranti",
	"lai cribe pu finti le vi cukta",
	// 6.4
	"lo ratcu cu bunre",
	"loi ratcu cu cmalu",
	"lo'i ratcu cu barda",
	"mi fadni zo'e lo'i lobypli",
	// 6.5
	"lo'e cinfo cu xabju le fi'ortu'a",
	"lo'e glipre cu xabju le fi'ortu'a na.e le gligugde",
	"le'e xelso merko cu gusta ponse",
	"le'e skina cu se finti ne'i la xali,uyd",
	// 6.6
	"do cadzu le bisli",
	"re do cadzu le bisli",
	"mi ponse su'o ci cutci",
	"ro do cadzu le bisli",
	"mi cusku lu do cadzu le bisli li'u",
	"mi cusku ro lu do cadzu le bisli li'u",
	"mi cusku su'o lu do cadzu le bisli li'u",
	"mi cusku re lu do cadzu le bisli li'u",
	"re le gerku cu blabi",
	"re le ci gerku cu blabi",
	"le ci gerku cu blabi",
	"ro le ci gerku cu blabi",
	"ci lo gerku cu blabi",
	"ci lo ro gerku cu blabi",
	"so'o lo ci gerku cu blabi",
	// 6.8
	"ci gerku cu blabi",
	"ci gerku ku cu blabi",
	"mi ponse su'o ci lo cutci",
	// 6.9
	"re do cu nanmu",
	"le re do cu nanmu",
	"re le ci cribe cu bunre",
	"le re le ci cribe cu bunre",
	"pa le re le ci cribe cu bunre",
	// 6.10
	"mi viska lu le xunre cmaxirma li'u",
	"mi viska le selsinxa be lu le xunre cmaxirma li'u",
	"mi viska la'e lu le xunre cmaxirma li'u",
	"mi viska la'e lu le xunre cmaxirma li'u lu'u",
	"mi pu cusku lu'e le vi cukta",
	"mi pu cusku le sinxa be le vi cukta",
	"mi troci tu'a le vorme",
	"lo'i ratcu cu barda .iku'i lu'a ri cmalu",
	"lo ratcu cu cmalu .i ku'i lu'i ri barda",
	"mi ce do girzu .i lu'o ri gunma .i vu'i ri porsi",
	"mi viska na'e bo le gerku",
	"mi nelci loi glare cidja .ije do nelci to'ebo ri .ije la djein nelci no'ebo ra",
	// 6.11
	"coi",
	"je'e",
	"coi djan",
	"doi djan",
	"coi xunre pastu nixli",
	"co'o la bab .e la noras",
	"coi le xunre pastu nixli",
	"doi la djan",
	"doi djan ko klama mi",
	"ko klama mi doi djan",
	// 6.12
	"la djonz klama le zarci",
	"lai djonz klama le zarci",
	// corrected to remove glides
	"doi djan pol djonz le bloti cu klama fi la niiuport niiuz",
	// 6.13
	"mi prami do",
	"le cribe goi ko'a cu xekri .i ko'a citka le smacu",
	"ro da poi prenu cu prami pa de poi finpe",
	"le cribe cu batci vo'a",
	"mi klama la frankfurt ri",
	"mi klama la frankfurt zo'e zo'e zo'e",
	"ko muvgau ti ta tu",
	"li re su'i re du li vo .i la'e di'u jetnu",
	"mi viska le mlatu ku poi zo'e zbasu ke'a loi slasi",
	"do klama ma",
	// added to test "In addition, sequences of lerfu words (of selma'o BY and related selma'o) can also be used as definable pro-sumti."
	"bycy broda dypa",
	// 6.14
	"mi cusku lu mi'e djan li'u",
	"mi cusku lo'u li mi le'u",
	"mi cusku zo ai",
	"mi cusku zoi kuot I'm John kuot",
	// 6.15
	"li vo",
	"li re su'i re",
	"li abu bi'epi'i xy bi'ete'a re su'i by bi'epi'i xy su'i cy",
	"me'o vo",
	"me'o re su'i re",
	// 7.1
	// (no Lojban examples)
	// 7.2
	"mi'e djan doi frank mi cusku lu mi bajra li'u do",
	"do klama le zarci",
	"ko klama le zarci",
	"mi viska ko",
	"mi viska le prenu poi prami ko",
	// 7.3
	"le ti bloti",
	"le vi bloti",
	"ti noi bloti",
	// 7.4
	"do na nelci loi mlatu .i di'u jitfa jufra",
	"la saimn cusku di'e",
	"dei jetnu jufra",
	"do'i jetnu jufra",
	"mi prami la djein .i mi nelci la'e di'u",
	"mi prami la djein .i mi nelci di'u",
	// 7.5
	"la alis klama le zarci .i ko'a blanu",
	"la alis klama le zarci .i ko'a goi la alis cu blanu",
	"la alis klama le zarci .i la alis goi ko'a cu blanu",
	"la alis goi ko'a klama le zarci .i ko'a cu blanu",
	"ti slasi je mlatu bo cidja lante gacri cei broda .i le crino broda cu barda .i le xunre broda cu cmalu",
	"mi klama cei brode le zarci .i do brode",
	"broda ke brode brodi",
	"mi viska le gerku .i gy cusku zo arf",
	"le ninmu goi la sam cu klama le zarci",
	// 7.6
	"la alis sipna ne'i le ri kumfa",
	"la alis sipna ne'i le la alis kumfa",
	"mi prami mi",
	"la djan viska le tricu .i ri se jadni le ri jimca",
	"lo smuci .i lo forca .i la rik pilno rixire .i la alis pilno riximu",
	"lo smuci .i lo forca .i la rik pilno ra .i la alis pilno ru",
	"la alis klama le zarci .i ri goi ko'a blanu",
	"xu zo djan cmene do .i go'i",
	"mi klama le zarci .i do go'i",
	"mi ba klama le zarci .i mi nelci le si'o mi go'i .i do go'e",
	"mi nelci le si'o go'i",
	"le xekri mlatu cu klama le zarci .i le go'i cu cadzu le bisli",
	"mi nupre le nu mi go'o .i ba dunda le jdini le bersa .i ba dunda le zdani le tixnu",
	"mi se pluka le nu do pensi le nu nei kei pu le nu do zukte",
	"mi ba klama ca le nu do no'a",
	"mi ba lumci le mi karce",
	"mi go'i",
	"mi go'i ra'o",
	"la djan cusku lu mi klama le zarci li'u .i la alis cusku lu mi go'i li'u",
	// 7.7
	"mi klama le bartu be le zdani le nenri be le zdani zu'i zu'i",
	"loi jmive cu se zbasu fi loi selci",
	"loi jmive cu se zbasu zo'e fi loi selci",
	"loi jmive cu se zbasu zi'o loi selci",
	"mi zbasu le dinju loi mudri",
	"zi'o zbasu le dinju loi mudri",
	"mi zbasu zi'o loi mudri",
	"mi zbasu le dinju zi'o",
	"mi troci le nu mi co'e le vorme",
	// 7.8
	"mi lumci vo'a",
	"mi klama le zarci vo'e",
	"mi prami do soi vo'a vo'e",
	"mi prami do soi vo'a",
	"mi bajykla ti ta soi vo'e .i mi bajykla ti ta soi vo'e vo'i .i soi vo'e vo'i mi bajykla ti ta",
	"mi bajykla ti soi vo'i se'u ta",
	// 7.9
	// duplicate: "do klama ma",
	"do mo",
	"ma cmene do",
	"doi ma",
	"lo mo prenu cu darxi do .i barda",
	"ma djuno ma",
	// 7.10
	"mi catlu lo mlatu poi zbasu ke'a lei slasi",
	"mi catlu lo mlatu poi zo'e zbasu ke'a lei slasi",
	"mi catlu lo mlatu poi zbasu lei slasi",
	"mi catlu lo mlatu poi ke'a zbasu lei slasi",
	// 7.11
	"le ka ce'u gleki",
	"le ka gleki ce'u",
	// 7.12
	"la djan cu lafmuvgau da poi grana ku'o gi'e desygau da",
	// 7.13
	// (no examples)
	// 7.14
	"ko'a du le nanmu",
	"ko'a mintu le nanmu",
	// 7.15
	"donta'a",
	"donma'o",
	// corrected to remove glides
	"fo'a goi le kulnrsu'omi .i lo fo'arselsanga",
	// 8.1
	"ti cu barda",
	"ti poi ke'a prenu ku'o cu barda",
	"ti poi ke'a nazbi ku'o cu barda",
	"ti poi ke'a nazbi kapkevna ku'o cu barda",
	"tu poi le mlatu pu lacpu ke'a ku'o cu ractu",
	"ta poi mi djica le nu mi ponse ke'a ku'o cu bloti",
	"ta poi mi djica le nu mi ponse ke'a kei ku'o cu bloti",
	"ti poi nazbi cu barda",
	"tu poi le mlatu pu lacpu cu ratcu",
	"ti poi prenu cu barda",
	// 8.2
	"le gerku poi blanu cu barda",
	"le gerku noi blanu cu barda",
	"mi noi pajni cu zvati",
	"xu do viska le mi karce noi blabi",
	"xu do viska le mi karce poi blabi",
	"xu do viska le mi blabi karce",
	// 8.3
	"le stizu pe mi cu blanu",
	"le stizu poi ke'a srana mi cu blanu",
	"le stizu po mi cu xunre",
	"le stizu poi ke'a se steci srana mi cu xunre",
	"le birka po'e mi cu spofu",
	"le birka poi jinzi ke se steci srana mi cu spofu",
	"le botpi po mi cu spofi",
	"le birka be mi cu spofu",
	"le gerku po'u le mi pendo cu cinba mi",
	"le gerku poi du le mi pendo cu cinba mi",
	"le mi pendo po'u le gerku cu cinba mi",
	"le tcadu po'u la nu,iork",
	"la nu,iork po'u le tcadu",
	"le kabri pe le mi pendo cu cmalu",
	"le mi pendo pe le kabri cu cmalu",
	"le blabi gerku ne mi cu batci do",
	"le nanmu no'u la djim cu terpemci",
	"le nanmu po'u la djim cu terpemci",
	"le nanmu cu punji le xance le daski",
	// 8.4
	"le gerki poi blabi zi'e poi batci le nanmu cu klama",
	"le gerku poi blabi zi'e noi le mi pendo cu ponse ke'a cu klama",
	"le botpi po mi zi'e poi blanu cu spofu",
	"mi ba zutse le stizu pe mi zi'e po do zi'e poi xunre",
	"mi ba citka le dembi pe mi zi'e poi cpana le mi palta zi'e noi do dunda ke'a mi",
	// 8.5
	"le gerku poi blabi cu klama",
	"le gerku voi blabi cu klama",
	// duplicate: "le nanmu cu ninmu",
	"ti voi nanmu cu ninmu",
	// 8.6
	"le gerku poi blabi ku'o ku cu klama vau",
	"le poi blabi ku'o gerku cu klama",
	"le gerku ku poi blabi cu klama",
	"re le mu prenu cu klama le zarci",
	"re le poi ninmu ku'o mu prenu cu klama le zarci",
	"re le mu prenu poi ninmu cu klama le zarci",
	"re le mu prenu poi ninmu ku cu klama le zarci",
	"re le mu prenu ku poi ninmu cu klama le zarci",
	"lo prenu ku noi blabi cu klama le zarci",
	"lo prenu noi blabi cu klama le zarci",
	"lo prenu noi blabi ku cu klama le zarci",
	"mi viska la nanmu poi terpa le ke'a xirma ku",
	"mi viska la nanmu ku poi terpa le ke'a xirma",
	"mi ponse re karce poi xekri",
	"mi ponse re karce ku poi xekri",
	// 8.7
	"le mi karce cu xunre",
	"le pe mi karce cu xunre",
	"le karce pe mi cu xunre",
	"le le nanmu ku karce cu blanu",
	"le li mu jdicu se bende",
	"le mi noi sipna vau karce cu na klama",
	"le mi karce poi sipna cu na klama",
	// 8.8
	"li pai noi na'e frinu namcu",
	"lu mi klama le zarci li'u noi mi cusku ke'a cu jufra",
	"la'e poi tolcitno vau lu le xunre cmaxirma li'u cu zvati le vu kumfa",
	"la'e lu le xunre cmaxirma li'u lu'u poi to'ercitno cu zvati le vu kumfa",
	"la frank e la djordj noi nanmu cu klama le zdani",
	"la frank e la djordj vu'o noi nanmu cu klama le zarci",
	"la frank e la djordj noi pu bajra cu klama le zdani",
	"la frank e la djordj vu'o noi pu bajra cu klama le zdani",
	// 8.9
	"coi frank",
	"co'o xirma",
	"fi'i la frank e la djordj",
	"coi la frank",
	"coi frank poi xunre se bende",
	"co'o poi mi zvati ke'a ku'o xirma",
	"co'o xirma poi mi xirma",
	// 8.10
	"le prenu poi zvati le kumfa poi blanu cu masno",
	"le prenu poi zvati le kumfa poi ke'axire zbasu ke'a cu masno",
	"le prenu poi ke'a goi ko'a zo'u ko'a zvati le kumfa poi ke'a goi ko'e zo'u ko'a zbasu ko'e cu masno",
	// 9.1
	// (no examples)
	// 9.2
	"mi cu klama la bastn la atlantas le dargu le karce",
	"mi la bastn la atlantas le dargu le karce cu klama",
	"mi la bastn cu klama la atlantas le dargu le karce",
	"klama la bastn la atlantas le dargu le karce",
	"mi klama la bastn la atlantas",
	"mi klama la bastn la atlantas le karce",
	"mi klama la bastn la atlantas zo'e le karce",
	// 9.3
	"fa mi cu klama fe la bastn fi la atlantas fo le dargu fu le karce",
	"fa mi klama fe le zdani be mi be'o poi nurma vau fi la nu,IORK",
	"klama fa mi fi la atlantas fu le karce fe la bastn fo le dargu",
	"fu le karce fo le dargu fi la atlantas fe la bastn cu klama fa mi",
	"le karce le dargu la atlantas la bastn cu klama mi",
	"mi klama fi la atlantas le dargu fe la bastn le karce",
	"la rik fa la djein klama le kindi'u fe le zdani fe le zarci",
	"fa la rik fa la djein klama fe le kindi'u fe le zdani fe le zarci",
	"fi'a do dunda le vi rozgu",
	"fi'a do dunda fe le vi rozgu",
	// 9.4
	"la bastn cu se klama mi",
	"fe la bastn cu klama fa mi",
	"le klama",
	"le se klama",
	"le te klama",
	"le ve klama",
	"le xe klama",
	"mi se ke blanu zdani ti",
	"mi se ke blanu zdani ke'e ti",
	// 9.5
	"mi viska do fi'o kanla le zunle",
	"mi viska do fi'o kanla fe'u le zunle",
	"mi viska do fi'o se pilno le zunle kanla",
	// 9.6
	"mi viska do sepi'o le zunle kanla",
	"la eivn cu vecnu loi flira cinta ka'a mi",
	"mi cadzu seka'a la bratfyd",
	"bloti teka'a la nu,IORK",
	"do bajra veka'a lo djine",
	"mi citka xeka'a le vinji",
	"lo nanmu be do'e le berti cu klama le tcadu",
	// 9.7
	"le spati cu banro ri'a le nu do djacu dunda fi le spati",
	"la djan cpacu le pamoi se jinga ki'u le nu la djan jinga",
	"mi lebna le cukta mu'i le nu mi viska le cukta",
	"la sokrates morsi binxo ni'i le nu la sokrates remna",
	"do djacu dunda fi le spati seri'a le nu ri banro",
	"le nu do djacu dunda fi le spati cu rinka le nu le spati cu banro",
	"le spati cu banro .i ri'abo do djacu dunda fi le spati",
	"do djacu dunda fi le spati .i seri'abo le spati cu banro",
	"le spati cu banro .i ri'a do djacu dunda fi le spati",
	// 9.8
	"mi jgari lei djacu .i ri'abo mi jgari le kabri",
	"ri'agi mi jgari le kabri gi mi jgari lei djacu",
	"seri'agi mi jgari lei djacu gi mi jgari le kabri",
	"mi jgari ri'agi le kabri gi lei djacu",
	"mi dunda le cukta la djan .imu'ibo la djan dunda lei jdini mi",
	"nu'i mu'igi la djan lei jdini mi gi mi le cukta la djan nu'u dunda",
	"mi mu'igi viska le cukta gi lebna le cukta",
	"mi mu'igi viska gi lebna vau le cukta",
	"mi le cukta mu'igi viska gi lebna",
	"li ny du li ni'igi vei re su'i re gi vo",
	"li ny du li ni'igi vei re su'i re ve'o gi vo",
	// 9.9
	"mi tavla bau la lojban bai tu'a la frank",
	"mi tavla bau la lojban bai",
	"mi tavla bau la lojban baiku",
	"mi tavla bau bai tu'a la frank",
	"mi tavla bauku bai tu'a la frank",
	"bau bai ku mi tavla",
	"bauku bai ku mi tavla",
	"mi bai tavla bau la lojban",
	"mi se bapli tavla bau la lojban",
	"mi fi'o kanla fe'u viska do",
	"mi bai ke ge klama le zarci gi cadzu le bisli",
	"mi bai ke ge klama le zarci gi cadzu le bisli ke'e",
	"bai tu'e mi klama le zarci .i mi cadzu le bisli",
	"bai tu'e mi klama le zarci .i mi cadzu le bisli tu'u",
	// 9.10
	// apasionatas changed to apasi'onatas to avoid glide
	"la apasi'onatas poi se cusku la artr rubnstain cu se nelci mi",
	"la apasi'onatas noi se finti la betovn cu nelci mi",
	"la apasi'onatas pe la artr rubnstain se nelci mi",
	"la apasi'onatas ne la betovn se nelci mi",
	"la apasi'onatas pe cu'u la artr rubnstain cu se nelci mi",
	"la apasi'onatas ne fi'e la betovn cu se nelci mi",
	"la frank nelci la betis nesemau la meiris",
	"la frank nelci la meiris neseme'a la betis",
	"la frank nelci la meiris seme'a la betis",
	"le ni la frank nelci la betis cu zmadu le ni la frank nelci la meiris",
	// 9.11
	"mi nelci do .ije mi nelci la djein",
	"mi nelci do .iki'ubo mi nelci la djein",
	"mi nelci do .ijeki'ubo mi nelci la djein",
	"mi nelci do .eki'ubo la djein",
	"mi nelci do gi'eki'ubo nelci la djein",
	"mi bevri le dakli .ijeseri'abo tu'e mi bevri le gerku .ijadu'ibo mi bevri le mlatu",
	"mi bevri le dakli .ijeseri'abo tu'e mi bevri le gerku .ijadu'ibo mi bevri le mlatu tu'u",
	"mi bevri le dakli gi'eseri'ake bevri le gerku gi'adu'ibo bevri le mlatu",
	"mi bevri le dakli gi'eseri'ake bevri le gerku gi'adu'ibo bevri le mlatu ke'e",
	"mi bevri le dakli .eseri'ake le gerku adu'ibo le mlatu",
	"mi bevri le dakli .eseri'ake le gerku adu'ibo le mlatu ke'e",
	// 9.12
	"mi cusku bau la lojban",
	"la lojban jaibau cusku fai mi",
	"le nu mi lebna le cukta cu se krinu le nu mi viska le cukta",
	"mi jai se krinu le nu mi viska le cukta kei",
	"mi jai se krinu le nu mi viska le cukta kei fai le nu mi lebna le cukta",
	// 9.13
	"mi nelci do mu'inai le nu do nelci mi",
	"le spati cu banro na'emu'i le nu do djacu dunda fi le spati",
	// 9.14
	"mi tavla bau la lojban bai ki tu'a la frank .ibabo mi tavla bau la gliban",
	"mi tavla bau la lojban bai tu'a la frank .ibabo mi tavla bau la gliban bai tu'a la frank",
	"mi ki tavla",
	// 9.15
	"la frank bajra seka'a le zdani .ije la frank bajra teka'a le zdani",
	"la frank bajra seka'a je teka'a le zdani",
	"la frank bajra seka'a le zdani ce'e teka'a le zdani",
	// 10.1
	// duplicate: "mi klama le zarci",
	"mi cu pu klama le zarci",
	"puku mi klama le zarci",
	"mi klama puku le zarci",
	"mi klama le zarci pu",
	"mi klama le zarci puku",
	// 10.2
	"le nanmu va batci le gerku",
	"le nanmu zu'a batci le gerku",
	"le nanmu zu'avi batci le gerku",
	"zu'aviku le nanmu cu batci le gerku",
	// 10.3
	"le nanmu ga'u zu'a batci le gerku",
	"le nanmu zu'a ga'u batci le gerku",
	"le nanmu zu'avi ga'uvu batci le gerku",
	"le nanmu vi zu'a batci le gerku",
	"le nanmu ca'u vi ni'a va ri'u vu ne'i batci le gerku",
	// 10.4
	"le nanmu pu batci le gerku",
	"le nanmu puzi batci le gerku",
	"le nanmu pu pu batci le gerku",
	"le nanmu ba puzi batci le gerku",
	"le nanmu zi pu batci le gerku",
	"le nanmu zu batci le gerku",
	"le nanmu puzu vu batci le gerku",
	"le nanmu cu batci le gerku puzuvuku",
	// 10.5
	"le verba ve'i cadzu le bisli",
	"le verba ze'a cadzu le bisli",
	"le verba pu ze'a cadzu le bisli",
	"mi ca ze'ica cusku dei",
	"mi ca ze'ipu cusku dei",
	"mi pu ze'aba citka le mi sanmi",
	"mi pu ze'aca citka le mi sanmi",
	"ta ri'uve'i finpe",
	"ta ri'u ve'ica'u finpe",
	// 10.6
	// duplicate: "mi pu klama le zarci",
	"le tricu ba crino",
	// 10.7
	"le verba ve'a vi'a cadzu le bisli",
	// 10.8
	"le verba mo'i ri'u cadzu le bisli",
	"le verba ri'u cadzu le bisli",
	"le verba mo'i ri'u cadzu le bisli ma'i vo'a",
	"le verba zu'avu mo'i ri'uvi cadzu le bisli",
	"mi mo'i ca'uvu citka le mi sanmi",
	// 10.9
	"mi puzu ze'u velckule",
	"mi puzu ze'u di'i velckule",
	"mi ba ta'e klama le zarci",
	"mi na'o klama le zarci",
	"le verba ru'inai cadzu le bisli",
	"mi paroi klama le zarci",
	"mi du'eroi klama le zarci",
	"mi pu reroi klama le zarci",
	"le ratcu reroinai citka le cirla",
	"mi ze'e paroi klama le zarci",
	"mi ze'epu noroi klama le zarci",
	// 10.10
	"mi pu'o damba",
	"la stiv ca'o bacru",
	"le verba ba'o cadzu le bisli",
	"mi ba co'a citka le mi sanmi",
	"mi pu co'u citka le mi sanmi",
	"mi ba di'i co'a bajra",
	"mi pu mo'u citka le mi sanmi",
	"mi pu de'a citka le mi sanmi",
	"mi ba di'a citka le mi sanmi",
	"le ctuca pu za'o ciksi le cmaci seldanfu le tadgri",
	"la djan pu co'i catra la djim",
	"mi pare'u klama le zarci",
	"mi pare'u paroi klama le zarci",
	"mi paroi pare'u klama le zarci",
	// 10.11
	"ko vi'i fe'e di'i sobmo le gurmi",
	"mi fe'e ciroi tervecnu lo selsalta",
	"ze'e roroi ve'e fe'e roroi ku li re su'i re du li vo",
	"tu ve'abe'a fe'e co'a rokci",
	// 10.12
	"mi klama le zarci ca le nu do klama le zdani",
	"mi klama le zarci pu le nu do pu klama le zdani",
	"le ratcu cu citka le cirla vi le panka",
	"le ratcu cu citka le cirla vi le vu panka",
	"le ratcu cu citka le cirla vu le vi panka",
	"mi morsi ba'o le nu mi jmive",
	"mi morsi ba le nu mi jmive",
	"mi klama le zarci pu'o le nu mi citka",
	"mi klama le zarci ba'o le nu mi citka",
	"le bloti pu za'o xelklama fe'e ba'o le lalxu",
	"mi klama le zarci reroi le ca djedi",
	"loi snime cu carvi ze'u le ca dunra",
	"loi snime cu carvi ca le ze'u dunra",
	// 10.13
	"mi puki klama le zarci .i le nanmu cu batci le gerku",
	"mi puki klama le zarci .i le nanmu pu batci le gerku",
	"mi pu klama le zarci .i le nanmu pupu batci le gerku",
	"puku mi ba klama le zarci",
	"mi puba klama le zarci",
	"mi ba klama le zarci puku",
	"mi bapu klama le zarci",
	"pukiku mi ba klama le zarci .i le nanmu cu batci le gerku",
	"mi pu klama le ba'o zarci",
	"mi ca jinvi ledu'u mi ba morsi",
	// 10.14
	"puzukiku ne'i ki le kevna le ninmu goi ko'a zutse le rokci",
	".i ko'a citka loi kanba rectu",
	".i ko'a pu jukpa ri le mudyfagri",
	".i lei rectu cu zanglare",
	".i le labno goi ko'e bazaki nenri klama le kevna",
	".i ko'e lebna lei rectu ko'a",
	".i ko'e bartu klama",
	// 10.15
	"la djan ca cusku lesedu'u la djordj ca klama le zarci",
	"la djan ca cusku lesedu'u la djordj pu klama le zarci",
	"la djan pu cusku lesedu'u la djordj ca klama le zarci",
	"la djan pu cusku lesedu'u la djordj pu klama le zarci",
	"la djan pu cusku lesedu'u la alis pu cusku lesedu'u la djordj pu cusku lesedu'u la maris nau klama le zarci",
	// 10.16
	"le verba cu cadzu le bisli zu'a le nu le nanmu cu batci le gerku",
	"le nanmu cu batci le gerku .izu'abo le verba cu cadzu le bisli",
	"le nanmu cu batci le gerku .i zu'a la'e di'u le verba cu cadzu le bisli",
	"le nanmu cu batci le gerku .i zu'a le verba cu cadzu le bisli",
	"le nanmu cu batci le gerku .izu'aku le verba cu cadzu le bisli",
	"pugi mi klama le zarci gi mi klama le zdani",
	"mi klama pugi le zarci gi le zdani",
	"mi pugi klama le zarci gi klama le zdani",
	// 10.17
	"la teris satre le mlatu .ije la teris satre le ractu",
	"la teris satre le mlatu gi'e satre le ractu",
	"la teris satre le mlatu e le ractu",
	"la teris satre le mlatu .ijebabo la teris satre le ractu",
	"la teris satre le mlatu gi'ebabo satre le ractu",
	"la teris satre le mlatu .ebabo le ractu",
	"mi bevri le dakli .ije tu'e mi bevri le gerku .ija mi bevri le mlatu tu'u",
	"mi bevri le dakli gi'eke bevri le gerku gi'a bevri le mlatu",
	"mi bevri le dakli eke le gerku a le mlatu",
	"mi bevri le dakli .ijeba tu'e mi bevri le gerku .ijacabo mi bevri le mlatu tu'u",
	"mi bevri le dakli gi'e bake bevri le gerku gi'a cabo bevri le mlatu",
	"mi bevri le dakli gi'e bake bevri le gerku gi'a cabo bevri le mlatu ke'e",
	"mi bevri le dakli ebake le gerku a cabo le mlatu",
	"mi bevri le dakli ebake le gerku a cabo le mlatu ke'e",
	// 10.18
	"mi punai klama le zarci",
	"mi klama le zarci canai le nu do klama le zdani",
	"le nanmu cu batci le gerku ne'inai le kumfa",
	"mi morsi ca'onai le nu mi jmive",
	"mi na'e pu klama le zarci",
	"le nanmu cu batci le gerku to'e ne'i le kumfa",
	"mi klama le zarci na'e ca le nu do klama le zdani",
	"mi morsi na'e ca'o le nu mi jmive",
	"le verba na'e ri'u cadzu le bisli",
	// 10.19
	"ro datka cu flulimna",
	"ro datka ca flulimna",
	"ro datka ca ca'a flulimna",
	"ro datka ka'e flulimna",
	"la djan ka'e viska",
	"le cukta ka'e viska",
	"ro cifydatka nu'o flulimna",
	"la frank pu'i viska",
	"mi pu ca'a klama le zarci",
	"la frank ba nu'o klama le zdani",
	"ta jelca",
	"ta ca ca'a jelca",
	"ta ka'e jelca",
	"jelca",
	// 10.20
	"mi pu je ba klama le zarci",
	"mi pu klama le zarci .ije mi ba klama le zarci",
	"mi punai je canai je ba klama le zarci",
	"mi ba klama le zarci",
	"mi mo'izu'anai je mo'iri'u cadzu",
	"mi mo'izu'a naje mo'iri'u cadzu",
	"mi puza bi'o bazu vasxu",
	// 10.21
	"mi reroi pi'u xaroi celgau le seldanti",
	"la djordj ca'o co'a ciska",
	"mi reroi ca'o xaroi darxi le damri",
	// 10.22
	"mi cu klama le zarci",
	"le zarci cu se klama mi",
	// duplicate: "le ratcu cu citka le cirla vi le panka",
	"le panka cu jai vi citka le cirla fai le ratcu",
	"fa mi cu klama fe le zarci",
	"fe le zarci cu klama fa mi",
	// duplicate: "mi cu klama le zarci",
	"mi viska le jai vi citka be le cirla",
	"mi djuno fi le jai ca morsi be fai la djan",
	// 10.23
	"mi nelci do mu'i le nu do nelci mi",
	"mi nelci do ba le nu do nelci mi",
	"le nu do nelci mi cu mukti le nu mi nelci do",
	"le nu mi nelci do cu balvi le nu do nelci do",
	"mi nelci do .imu'ibo do nelci mi",
	"do nelci mi .ibabo mi nelci do",
	"mu'igi do nelci mi gi mi nelci do",
	"bagi do nelcimi gi mi nelci do",
	// 10.24
	"do klama le zdani ca ma",
	"le verba vi ma pu cadzu le bisli",
	"le nanmu cu'e batci le gerku",
	"va",
	"puzu",
	"vi le lunra",
	"pu'o",
	"seka'a le briju",
	"do puzi je cu'e sombo le gurni",
	"la artr pu je'i ba nolraitru",
	// 10.25
	"la frank sanli zu'a nu'i la djordj la'u lo mitre be li mu",
	"la frank sanli zu'a nu'i la djordj la'u lo mitre be li mu nu'u",
	"la frank sanli zu'a nu'i la'u lo mitre be li mu",
	"la frank sanli zu'a nu'i la'u lo mitre be li mu nu'u",
	// 10.26
	"a'o do pu seju ba roroi ca'o fe'e su'oroi jimpe fi le lojbo temci selsku ciste",
	// 11.1
	// duplicate: "mi klama le zarci",
	"nu mi klama le zarci",
	"nu mi klama le zarci kei",
	"la djan cu nu sonci kei djica",
	"la djan cu djica le nu sonci",
	"la djan cu djica le nu sonci kei",
	// 11.2
	// duplicate: "le klama",
	// duplicate: "le se klama",
	// duplicate: "le te klama",
	// duplicate: "le ve klama",
	// duplicate: "le xe klama",
	"le nu klama",
	"le nu mi vasxu",
	"le nu la djan cinba la djein",
	"mi nelci le nu limna",
	"mi nelci le nu mi limna",
	"le se nelci cu cafne",
	"la lojban cu frili mi le nu mi tadni",
	"la lojban cu frili mi le nu mi tadni kei",
	// 11.3
	"le mu'e la djan catra la djim cu zekri",
	"ca'o le pu'u le latmo balje'a cu porpi kei so'i je'atru cu selcatra",
	"mi tatpi ri'a le zu'o mi plipe",
	"mi tatpi ri'a le zu'o mi plipe kei",
	"le za'i mi jmive cu ckape do",
	"le za'i mi jmive kei cu ckape do",
	// 11.4
	"la djan cu se risna zo'e",
	"la djan cu ckaji le ka se risna",
	"la djan cu ckaji le ka se risna kei",
	"la djan cu ckaji le ka se risna zo'e",
	"la djan cu ckaji le ka se risna zo'e kei",
	"do cnino mi le ka xunre",
	"do cnino mi le ka xunre kei",
	"ka mi prami",
	"ka mi prami zo'e",
	"ka mi prami kei",
	"ka mi prami zo'e kei",
	"ka prami mi",
	"ka zo'e prami mi",
	"ka prami mi kei",
	"ka zo'e prami mi kei",
	"la djan cu zmadu la djordj le ka mi prami",
	"la djan cu zmadu la djordj le ka prami mi",
	"la djan cu zmadu la djordj le ka mi prami ce'u",
	"la djan cu zmadu la djordj le ka ce'u prami mi",
	"le ka dunda le xirma",
	"le ka zo'e dunda le xirma",
	"le ka zo'e dunda le xirma zo'e",
	"le ka zo'e dunda le xirma zo'e kei",
	"le ka ce'u dunda le xirma",
	"le ka ce'u dunda le xirma zo'e",
	"le ka ce'u dunda le xirma kei",
	"le ka ce'u dunda le xirma zo'e kei",
	"le ka dunda le xirma ce'u",
	"le ka zo'e dunda le xirma ce'u",
	"le ka dunda le xirma kei",
	"le ka zo'e dunda le xirma ce'u kei",
	// 11.5
	"le ni le pixra cu blanu",
	"le ni le pixra cu blanu kei",
	"le ni la djein cu mamta",
	"le ni la djein cu mamta kei",
	"li pa vu'u mo'e le ni le pixra cu blanu",
	"li pa vu'u mo'e le ni le pixra cu blanu kei",
	// 11.6
	"le jei li re su'i re du li vo",
	"le jei li re su'i re du li vo kei",
	"le jei li re su'i re du li mu",
	"le jei li re su'i re du li mu kei",
	"mi ba jdice tu'a le jei la djordj cu zekri gasnu",
	"mi ba jdice tu'a le jei la djordj cu zekri gasnu kei",
	// 11.7
	"mi djuno le nu la frank cu bebna",
	"mi djuno le nu la frank cu bebna kei",
	"mi djuno tu'a le jei la frank cu bebna",
	"mi djuno tu'a le jei la frank cu bebna kei",
	"mi djuno le du'u la frank cu bebna",
	"mi djuno le du'u la frank cu bebna kei",
	"mi kucli ledu'u la frank cu bebna",
	"mi kucli ledu'u la frank cu bebna kei",
	"mi kucli tu'a le jei la frank cu bebna",
	"mi kucli tu'a le jei la frank cu bebna kei",
	"la djan cusku le se du'u la djordj klama le zarci",
	"la djan cusku le se du'u la djordj klama le zarci kei",
	"la djan cusku lu la djordj klama le zarci li'u",
	// 11.8
	"mi djuno ledu'u makau pu klama le zarci",
	"mi djuno ledu'u la djan kau pu klama le zarci",
	"mi djuno ledu'u ma pu klama le zarci",
	"mi djuno fi le pu klama be le zarci",
	"mi ba zgana le du'u la djan jikau la djordj cu zvati le panka",
	// 11.9
	"mi morji le li'i mi verba",
	"mi nelci le si'o la lojban cu mulno",
	"ko zgana le su'u le ci smacu cu bajra",
	"le nu mi klama",
	"le su'u mi klama kei be lo fasnu",
	// modified to remove glides
	"le su'u la iecu'as kuctai selcatra kei be lo sa'ordzifa'a ke nalmatma'e sutyterjvi",
	// 11.10
	"mi troci le nu gasnu le nu le vorme cu karbi'o",
	"mi troci le nu mi gasnu le nu le vorme cu karbi'o",
	// duplicate: "mi troci tu'a le vorme",
	"tu'a le vorme lu'u ki'a",
	"tu'a la djan cu cafne",
	"tu'a mi rinka le nu do morsi",
	"mi jai rinka le nu do morsi",
	"le jai rinka be le nu do morsi",
	"le jai gau rinka be le nu do morsi",
	// 11.11
	// (no examples)
	// 11.12
	"le mikce cu se cinri le pu'u jenai za'i mi sipna",
	// 12.1
	"ti fagri festi",
	"ti fagyfesti",
	// 12.2
	"la blabi zdani cu gerku be fa la spot bei la sankt berNARD be'o zdani la bil klinton",
	// 12.3
	// (no lojban examples)
	// 12.4
	// (no examples)
	// 12.5
	// (no lojban examples)
	// 12.6
	"la mon rePOS gerzda la spat",
	"la mon rePOS zdani la spat noi gerku",
	"la mon rePOS zdani la spat noi ke'a gerku zo'e",
	"la mon rePOS zdani la spat noi ke'a gerku la sankt berNARD",
	"la mon rePOS gerzda la spat noi ke'a gerku la sankt berNARD ku'o la sankt berNARD",
	// 12.7
	"di'e jdaselsku la dong",
	// 12.8
	// (no lojban examples)
	// 12.9
	// (no lojban examples)
	// 12.10
	"la djak cu blakanla",
	"la djak cu se blakanla",
	// 12.11
	"bakni rectu panlo",
	"ke bakni rectu ke'e panlo",
	"bakni ke rectu panlo",
	"bakni ke rectu panlo ke'e",
	"zekri ke nenri klama",
	"zekri nenri klama",
	"ke zekri nenri ke'e klama",
	"xamsi ke calku curnu",
	"xamsi calku curnu",
	"ke xamsi calku ke'e curnu",
	// 12.12
	"nu sonci kei djica",
	"nunsoidji",
	// duplicate: "mi jai rinka le nu do morsi",
	"mi jaxri'a le nu do morsi",
	// 12.13
	// (no lojban examples)
	// 12.14
	"xance pilno minde",
	"ke xance pilno ke'e minde",
	"minde xance pilno",
	"ke minde xance ke'e pilno",
	"minde ke xance pilno",
	"minde ke xance pilno ke'e",
	// 12.15
	"mi citmau do lo nanca be li xa",
	"do citme'a mi lo nanca be li xa",
	"mi ca tsamau",
	"mi ca tsaze'a",
	"la djudis cu citrai lo'i lobypli",
	"la ainctain cu balrai lo'i skegunka",
	// 12.16
	"xekri",
	"jbena",
	"rinka",
	"cinfo",
	// 13.1
	"ui la djan klama",
	"uu la djan klama",
	"a'o la djan klama",
	"ue la djan klama",
	"ianai la djan klama",
	// 13.2
	"ua mi facki fi le mi mapku",
	"u'a mi cafki fi le mi mapku",
	"ui mi facki fi le mi mapku",
	"uo mi facki fi le mi mapku",
	"uu do cortu",
	"u'u do cortu",
	// duplicate: "ue la djan klama",
	"uecu'i la djan klama",
	"uenai la djan klama",
	"oi la djan klama",
	"o'onai la djan klama",
	"o'i la djan klama",
	"o'ecu'i la djan klama",
	"o'u la djan klama",
	"ii smacu",
	"la djan iu klama",
	"la djan ionai klama",
	"la djan klama iu",
	// 13.3
	"a'a da zgana le veltivni",
	"a'enai do ranji bacru",
	"ai mi muvgau do le ckana",
	"a'i mi ba gasnu le nu do cikna binxo",
	"a'o mi kanryze'a ca le bavlamdei",
	"au mi sipna",
	"a'ucu'i do pante",
	"e'a do sazri le karce",
	"e'e mi lifri tu'a do",
	"ei mi tisygau le karce ctilyvau",
	"e'o ko ko kurji",
	"e'u do klama le panka",
	"ianai do pu pensi le nu tcica mi",
	"do i'anai na xruti do le zdani",
	"ie mi na cusku lu'e le tcika be le nu xruti",
	"i'enai do i'e zukte",
	"do sazri le karce .i e'a",
	// 13.4
	"ei",
	"eicai",
	"eisai",
	"eiru'e",
	"eicu'i",
	"einai",
	// 13.5
	// (no examples)
	// 13.6
	// (no examples)
	// 13.7
	"ko ga'inai nenri klama le mi zdani",
	"ko ga'icu'i nenri klama le mi zdani",
	"ko ga'i nenri klama le mi zdani",
	"ga'i le xarju pu citka",
	"ause'i",
	"ause'inai",
	"o'onai ri'enai",
	"uiro'obe'unai",
	"le cukta be'u cu zvati ma",
	"e'ese'a",
	"e'ese'anai",
	"e'enaise'a",
	"e'enaise'anai",
	// 13.8
	"ie ge'eru'e",
	"mi e ui nai do",
	"mi enai ui do",
	// 13.9
	"mi pu tavla do o'onai oi",
	// 13.10
	"iepei",
	"iare'epei",
	"aipei",
	"aicai",
	"e'apei",
	"pei.o'u",
	"pei.o'ucu'i",
	"pei.o'usai",
	"oiro'odai",
	"le bloti iidai uu pu klama le xasloi",
	"o'onai bu'o",
	"iu bu'onai uinai",
	"mi ca ba'o prami do ja'e le nu mi badri",
	// 13.11
	"ca'e le re do cu simxu speni",
	"ba'acu'i le tuple be mi cu se cortu",
	"ti'e la uengas cu zergau",
	"za'a do tatpi",
	"pe'i la kartagos ei se daspo",
	"ru'a doi livinston",
	// 13.12
	"mi po'o darxi le mi tamne fo le nazbi",
	"mi darxi le mi tamne fo le nazbi",
	"mi darxi po'o le mi tamne fo le nazbi",
	"mi darxi le mi tamne ku po'o fo le nazbi",
	"mi darxi le mi tamne fo le nazbi ku po'o",
	"ganai da'i do viska le mi citno mensi gi ju'o do djuno ledu'u ri pazvau",
	"ganai da'inai do viska le mi citno mensi gi ju'o do djuno ledu'u ri pazvau",
	// 13.13
	"mi nelci le ctuta .i le ki'a ctuca",
	"mi viska le blanu pe'a zdani",
	"mi djuno ledu'u dakau klama le zarci",
	// 13.14
	"coi co'o ju'i nu'e ta'a pe'u ki'e fi'i be'e re'i mu'o je'e vi'o ke'o fe'o mi'e",
	"mi'enai djan",
	"ta'apei",
	// 13.15
	// TODO erasure
	// "la rik e la alis nerkla le kafybarja .i sei la rik cusku se'u ta'a ro zvati be ti mi ba za speni ti iu .i sei la djordj cusku se'u a'o ko gleki doi ma .i sei la pam cusku se'u pe'u alis xu mi ba terfriti le nunspenybi'o .i sei la mark cusku se'u coi ba za speni a'o le re do lifri le ka gleki .i sei la rik cusku se'u mi'e rik doi terpreti .i sei la alis cusku se'u nu'e pam o'ero'i do ba zvati .i sei la fred cusku se'u uinaicai ro'i mi ji'a prami la alis fe'o rik .i la fred cliva .i sei la rik cusku fi'i ro zvati ko pinxe pa ckafi fi'o pleji mi .i sei la pam cusku se'u be'e selfu .i sei le selfu cu cusku se'u re'i .i sei la pam cusku se'u e'o ko selfu le traji xamgu ckafi le ba za speni fi'o pleji mi .i sei le selfu fu cusku se'u vi'o .i sei la rik cusku se'u ki'e pam .i sei la pam cusku se'u je'e .i sei la djan cusku se'u y mi y mutce spopa y le nu le speni si y ba speni y y su yyyyyy mu'o .i sei la djordj cusku se'u ke'o djan zo'o",
	// modified for now:
	"la rik e la alis nerkla le kafybarja .i sei la rik cusku se'u ta'a ro zvati be ti mi ba za speni ti iu .i sei la djordj cusku se'u a'o ko gleki doi ma .i sei la pam cusku se'u pe'u alis xu mi ba terfriti le nunspenybi'o .i sei la mark cusku se'u coi ba za speni a'o le re do lifri le ka gleki .i sei la rik cusku se'u mi'e rik doi terpreti .i sei la alis cusku se'u nu'e pam o'ero'i do ba zvati .i sei la fred cusku se'u uinaicai ro'i mi ji'a prami la alis fe'o rik .i la fred cliva .i sei la rik cusku fi'i ro zvati ko pinxe pa ckafi fi'o pleji mi .i sei la pam cusku se'u be'e selfu .i sei le selfu cu cusku se'u re'i .i sei la pam cusku se'u e'o ko selfu le traji xamgu ckafi le ba za speni fi'o pleji mi .i sei le selfu cu cusku se'u vi'o .i sei la rik cusku se'u ki'e pam .i sei la pam cusku se'u je'e .i sei la djan cusku se'u mu'o .i sei la djordj cusku se'u ke'o djan zo'o",
	// 14.1
	// (no lojban examples)
	// 14.2
	// (no examples)
	// 14.3
	// (no lojban examples)
	// 14.4
	"la djan nanmu .ija la djeimyz ninmu",
	"la djan nanmu .ije la djeimyz ninmu",
	"la djan nanmu .ijo la djeimyz ninmu",
	"la djan nanmu .iju la djeimyz ninmu",
	"la djan nanmu .inajo la djeimyz ninmu",
	"la djan nanmu .ijonai la djeimyz ninmu",
	"la djan nanmu .ijanai la djeimyz ninmu",
	"la djan ninmu .ijanai la djeimyz ninmu",
	"la djan nanmu .inaja la djeimyz ninmu",
	"la djan nanmu .iseju la djeimyz ninmu",
	// 14.5
	"la djan nanmu",
	// duplicate: "la djan nanmu .ija la djeimyz ninmu",
	"ga la djan nanmu gi la djeimyz ninmu",
	"ge la djan nanmu gi la djeimyz ninmu",
	"gu la djan nanmu gi la djeimyz ninmu",
	"ganai la djan nanmu gi la djeimyz ninmu",
	"le nu do cidja dunda fi le xarju cu rinka le nu ri ba banro",
	"gonai la djan nanmu gi la djeimyz ninmu",
	"go la djan nanmu ginai la djeimyz ninmu",
	"ge la djan nanmu ginai la djeimyz ninmu",
	"ganai la djan nanmu ginai la djeimyz ninmu",
	// 14.6
	"la djan klama le zarci .ije la alis klama le zarci",
	"la djan e la alis klama le zarci",
	"la djan .ije la alis klama le zarci",
	"la djan o la alis klama le zarci",
	"ga la djan gi la alis klama le zarci",
	"la djan na.a la alis klama le zarci",
	// 14.7
	"mi dotco .ije mi ricfu .ije mi nanmu",
	"mi dotco .ija mi ricfu .ija mi nanmu",
	"mi dotco .ijo mi ricfu .ijo mi nanmu",
	"mi nelci la djan .ije mi nelci la martas .ija mi nelci la meris",
	"ga ge mi nelci la djan gi mi nelci la martas gi mi nelci la meris",
	"ge mi nelci la djan gi ga mi nelci la martas gi mi nelci la meris",
	// 14.8
	"mi nelci la djan .ije mi nelci la martas .ijabo mi nelci la meris",
	"mi nelci la djan e la martas abo la meris",
	"mi nelci la djan ebo la martas abo la meris",
	"mi cinba do .ije do cinba mi .ijanai mi prami do .ijebo do prami mi",
	"mi cinba do .ijebo do cinba mi .ijanai mi prami do .ijebo do prami mi",
	"tu'e mi cinba do ije do cinba mi tu'u ijanai tu'e mi prami do .ije do prami mi",
	"tu'e mi cinba do ije do cinba mi tu'u ijanai tu'e mi prami do .ije do prami mi tu'u",
	"mi cinba do ije do cinba mi .ijanai tu'e mi prami do .ije do prami mi",
	"mi cinba do ije do cinba mi .ijanai tu'e mi prami do .ije do prami mi tu'u",
	"mi dzukla le zarci .e la zdani ake le ckule .e le briju",
	"mi dzukla le zarci .e la zdani ake le ckule .e le briju ke'e",
	"mi dotco .ijo mi ricfu .ije tu'e mi dotco .ijo mi nanmu",
	"mi dotco .ijo mi ricfu .ije tu'e mi dotco .ijo mi nanmu tu'u",
	"tu'e mi dotco .ijo mi ricfu tu'u .ije tu'e mi dotco .ijo mi nanmu",
	"tu'e mi dotco .ijo mi ricfu tu'u .ije tu'e mi dotco .ijo mi nanmu tu'u",
	// 14.9
	"mi klama le zarci .ije mi nelci la djan",
	"mi klama le zarci gi'e nelci la djan",
	"mi ricfu gi'e klama le zarci",
	"mi dunda le cukta do .ije mi lebna lo jdini do",
	"fi do fa mi dunda le cukte gi'e lebna lo jdini",
	"mi dunda le cukta gi'e lebna lo jdini vau do",
	// duplicate: "mi klama le zarci",
	"mi klama le zarci vau",
	"mi klama le zarci vau gi'e nelci la djan vau vau",
	"klama le zarci gi'e dzukla le briju",
	"klama la nu,IORK la finyks gi'e klama la nu,IORK la rom",
	"da klama la nu,IORK la finyks gi'e klama la nu,IORK la rom",
	// 14.10
	"mi nelci la djan gi'e nelci la martas gi'abo nelci la meris",
	"mi dzukla le zarci gi'e dzukla le zdani gi'a ke dzukla le ckule gi'e dzukla le briju",
	"mi dzukla le zarci gi'e dzukla le zdani gi'a ke dzukla le ckule gi'e dzukla le briju ke'e",
	"mi dejni lo rupnu la djan .inaja mi dunda le cukta la djan .ijabo mi lebna le cukta la djan",
	"mi dejni lo rupnu nagi'a dunda gi'abo lebna vau le ckuta vau la djan",
	"fi la djan fa mi dejni lo rupnu nagi'a dunda gi'abo lebna vau le cukta",
	"mi ge klama le zarci gi nelci la djan",
	"mi ge klama le zarci gi'e dzukla le zdani gi nelci la djan",
	"mi na ge klama le zdani gi dzukla le zdani",
	"mi ge dunda le cukta gi lebna lo jdini vau do",
	"ge klama le zarci gi dzukla le briju",
	"mi gonai le zarci cu klama gi le bisli cu dansu",
	// 14.11
	"mi klama le zarci ce'e le briju pe'e je le zdani ce'e le ckule",
	"mi klama le zarci le briju .ije mi klama le zdani le ckule",
	"mi pe'eja do ce'e le zarci cu klama le briju",
	"mi klama le birju .ija do le zarci cu klama le briju",
	"mi klama le zarci gi'e dzukla vau le briju",
	"mi klama nu'i ge le zarci le briju nu'u gi le zdani le ckule",
	"mi klama nu'i ge le zarci le briju nu'u gi le zdani le ckule nu'u",
	// 14.12
	"ti blanu zdani",
	"ti blanu je zdani",
	"ti blanu gi'e zdani",
	"ti blanu .ije ti zdani",
	"la alis cu blanu je zdani prenu",
	"la alis cu blanu prenu .ije la alis cu zdani prenu",
	"la teris cu ricfu je nakni jabo fetsi",
	"la teris cu ricfu ja pindi je ke nakni ja fetsi",
	"la teris cu ricfu ja pindi je ke nakni ja fetsi ke'e",
	"la teris cu ke ricfu ja pindi ke'e je ke nakni ja fetsi",
	"la teris cu ke ricfu ja pindi ke'e je ke nakni ja fetsi ke'e",
	"la alis gu'e ricfu gi fetsi",
	"la alis gu'e blanu gi zdani prenu",
	"mi viska pa mlatu .ije mi viska pa gerku",
	"mi viska pa mlatu e pa gerku",
	"mi viska pa mlatu je gerku",
	// 14.13
	"xu la faidon gerku",
	"go'i",
	"nago'i",
	"xu la faidon gerku gi'onai mlatu",
	"la alis gerku gi'i mlatu",
	"nagi'e",
	"gi'enai",
	"nagi'enai",
	"nagi'o",
	"gi'onai",
	"do djica tu'a loi ckafi ji loi tcati",
	"do djica tu'a ge'i loi ckafi gi loi tcati",
	"do cadzu gi'i bajra",
	"ganai ti ckafi gi ko bevri loi tcati mi .ije ganai ti tcati gi ko bevri loi ckafi mi",
	// 14.14
	"la djan joi la alis cu bevri le pipno",
	"le nanmu ku joi le ninmu cu klama le zarci",
	"le nanmu ku joi le ninmu ku cu klama le zarci",
	// duplicate: "ti blanu joi xunre bolci",
	"mi cuxna la alis la frank ce la alis ce la djeimyz",
	"ti liste mi ce'o do ce'o la djan",
	"la djeimyz bruna la djordj",
	"la djeimyz .e la djordj bruna",
	"la djeimyz joi la djordj cu bruna remei",
	"la djeimyz fa'u la djordj prami la meris fa'u la martas",
	"la djeimyz e la djordj prami la meris e la martas",
	"la djeimyz prami la meris. ije la djordj prami la meris .ije la djeimyz prami la martas .ije la djordj prami la martas",
	"la djeimyz ce'e la meris pe'e je la djordj ce'e la martas prami",
	"la djeimyz fa'u la djordj prami re mensi",
	// 14.15
	"lo'i ricfu ku jo'e lo'i dotco cu barda",
	"lo'i ricfu ku ku'a lo'i dotco cu cmalu",
	"lo'i ricfu ja dotco cu barda",
	"lo'i ricfu je dotco cu cmalu",
	"la djeimyz ce la djordj pi'u la meris cebo la martas cu prami se remei",
	"la djeimyz cebo la djordj pi'u la meris cebo la martas cu prami se remei",
	"mi joibo do ce la djan joibo la djein cu gunma se remei",
	// `nu'u` removed
	"mi ce'ebau la lojban pe'ejoi do ce'e bau la gliban casnu",
	"nu'i joigi mi bau la lojban gi do bau la gliban nu'u casnu",
	"la djan fa'u la frank cusku nu'i bau la lojban nu'u fa'u bai tu'a la djordj",
	// terminator indicated as elided in the CLL is ungrammatical: "la djan fa'u la frank cusku nu'i bau la lojban nu'u fa'u bai tu'a la djordj nu'u",
	"mi ba gasnu la'e di'e .i tu'e kanji lo ni cteki .ice'o lumci le karce .ice'o dzukansa le gerku tu'u",
	"mi jo'unai do cu remei",
	// duplicate: "do djica tu'a loi ckafi ji loi tcati",
	"joi",
	"a'unaisairo'o",
	// 14.16
	"mi ca sanli la drezdn bi'i la frankfurt",
	"mi cadzu ca la pacac bi'o la recac",
	"mi cadzu ca la recac sebi'o la pacac",
	"la jbama pu daspo la uacintyn mi'i lo minli be li muno",
	"mi ca sanli la drezdn ga'o bi'i ga'o la frankfurt",
	"mi ca sanli la drezdn ga'o bi'i ke'i la frankfurt",
	"mi ca sanli la drezdn ke'i bi'i ga'o la frankfurt",
	"mi ca sanli la drezdn ke'i bi'i ke'i la frankfurt",
	"do dicra e'a mi ca la daucac bi'onai la gaicac",
	"joigi la djan gi la alis bevri le pipno",
	"mi ca sanli ke'i bi'i ga'o gi la drezdn gi la frankfurt",
	// 14.17
	"vei ci a vo prenu cu klama le zarci",
	"vei ci a vo ve'o prenu cu klama le zarci",
	"vei ga ci gi vo prenu cu klama le zarci",
	"vei ga ci gi vo ve'o prenu cu klama le zarci",
	"li re su'i je pi'i re du li vo",
	"li re gu'e su'i gi pi'i re du li vo",
	"li no ga'o bi'i ke'i pa",
	"xy boi xi vei abu ce'o ebu",
	"xy boi xi vei abu ce'o ebu ve'o",
	// 14.18
	"la artr pu nolraitru .ije la artr ba nolraitru",
	"la artr pujeba nolraitru",
	"mi pu bi'o ba vasxu",
	"mi pu klama le zarci .ije mi pu tervecnu lo cidja",
	"mi pu klama le zarci .ijebabo mi pu tervecnu lo cidja",
	"la djan .ecabo la alis klama le zarci",
	"mi dzukla le zarci .epuke le zdani a le ckule",
	"mi dzukla le zarci .epuke le zdani a le ckule ke'e",
	"mi dunda le cukta gi'e babo lebna lo jdini vau do",
	"mi dzukla le zarci gi'e ca ke cusku zo'e la djan",
	"mi dzukla le zarci gi'e ca ke cusku zo'e la djan ke'e",
	"mi viska pa nanmu .ijebabo mi viska pa ninmu",
	"mi viska pa nanmu .ijebatu'e mi viska pa ninmu",
	"mi viska pa nanmu .ijebatu'e mi viska pa ninmu tu'u",
	"mi mikce jebabo ricfu",
	"vei ci ebabo vo tadni cu zvati le kumfa",
	"vei ci ebabo vo ve'o tadni cu zvati le kumfa",
	"mi pu ge klama le zarci gi tervecnu lo cidja",
	// 14.19
	// duplicate: "le mikce cu se cinri le pu'u jenai za'i mi sipna",
	"mi jinvi le du'u loi jmive cu zvati gi'onai na zvati vau la iupiter",
	"mi jinvi ledu'u loi jmive cu zvati la iupiter .ijonai mi jinvi ledu'u loi jmive na zvati la iupiter",
	// 15.1
	// (no lojban examples)
	// 15.2
	// duplicate: "mi klama le zarci",
	// duplicate: "mi na klama le zarci",
	"mi na ca klama le zarci",
	"mi cu na ca klama le zarci",
	// duplicate: "lo ca nolraitru be le fasygu'e cu na krecau",
	"ti na barda prenu co melbi mi",
	"mi na gleki le nu na klama le nu dansu",
	"mi nelci le na melbi",
	"mi nelci lo na ca nolraitru be le fasygu'e",
	"ti na na barda prenu co melbi mi",
	"ti barda prenu co melbi mi",
	"mi ta'e klama le zarci",
	"mi cu ta'e klama le zarci",
	"mi na klama le zarci ki'u lenu le karce cu spofu",
	"le nu mi na klama le zarci cu se krinu le nu le karce cu spofu",
	// 15.3
	// (no lojban examples)
	// 15.4
	// duplicate: "mi klama le zarci",
	// duplicate: "mi na'e klama le zarci",
	// duplicate: "mi na klama le zarci",
	"mi cadzu klama le zarci",
	"mi na'e cadzu klama le zarci",
	"mi cadzu na'e klama le zarci",
	"mi na'e ke cadzu klama le zarci",
	"mi na'e ke cadzu klama ke'e le zarci",
	"mi na'e ke sutra cadzu ke'e klama le zarci",
	"mi na'e ke sutra cadzu be le mi birka ke'e klama le zarci",
	"mi na'e ke sutra cadzu lemi birka",
	"mi na'e ke sutra cadzu ke'e lemi birka",
	"mi na'e ke sutra cadzu be lemi birka",
	"mi na'e ke sutra cadzu be lemi birka ke'e",
	// duplicate: "mi na'e klama le zarci",
	"mi nalkla le zarci",
	"lo ca nolraitru be le fasygu'e cu krecau",
	"lo ca nolraitru be le fasygu'e cu na'e krecau",
	"lo ca nolraitru be le fasygu'e cu nalkrecau",
	// duplicate: "lo ca nolraitru be le fasygu'e cu na krecau",
	// 15.5
	"le stizu cu na'e xunre",
	"le stizu cu dzukla be le zarci",
	"le stizu cu na'e xunre skari",
	"le stizu cu na'e xunre be ci'u loka skari",
	"le stizu cu na'e xunre be teci'e le skari",
	"le stizu cu na'e xunre be ci'e lo'i skari",
	"le stizu cu na'e xunre be le'a lo'i skari",
	"le stizu cu to'e xunre be ci'u loka skari",
	"ta melbi",
	"ta na'e melbi",
	"ta no'e melbi",
	"ta to'e melbi",
	// 15.6
	"no lo ca nolraitru be le fasygu'e cu krecau",
	"na'ebo lo ca nolraitru be le fasygu'e ce krecau",
	"mi klama to'ebo la bastn",
	// 15.7
	// duplicate: "mi na pu klama le zarci",
	// duplicate: "mi punai klama le zarci",
	"mi paroinai dansu le bisli",
	// 15.8
	"xu la djan pu klama la paris e la rom .i na go'i",
	"la djan na pu klama la paris e la rom",
	"la djan cu na pu klama la paris e la rom",
	"na ba go'i",
	"la djan na ba klama la paris e la rom",
	"la djan cu na ba klama la paris e la rom",
	"ba na go'i",
	"la djan ba na klama la paris e la rom",
	"la djan cu ba na klama la paris e la rom",
	"na'e go'i",
	"la djan pu na'eke klama la paris e la rom",
	"la djan cu pu na'eke klama la paris e la rom",
	"la djan pu na'eke klama ke'e la paris e la rom",
	"la djan cu pu na'eke klama ke'e la paris e la rom",
	// 15.9
	"xu na go'i",
	"xu la djan na pu klama la paris e la rom",
	"xu la djan cu na pu klama la paris e la rom",
	// duplicate: "go'i",
	// duplicate: "na go'i",
	"ja'a go'i",
	"mi ja'a klama le zarci",
	"ta je'a melbi",
	// 15.10
	"xu do sisti lezu'o do rapydarxi ledo fetspe",
	"na'i go'i",
	"go'i na'i",
	"go'i ji'una'iku",
	// 15.11
	"na go'i .ije na'e go'i .ije na'i go'i",
	// 16.1
	"mi viska le nanmu",
	// 16.2
	"viska mi",
	"zo'e viska mi",
	"da zo'u da viska mi",
	"da de zo'u da prami de",
	"da zo'u da prami da",
	"de zo'u de prami de",
	"da zo'u le da gerku cu viska mi",
	"da zo'u la ralf gerku",
	// 16.3
	"ro da zo'u da viska mi",
	"ro da ro de zo'u da prami de",
	"ro da de zo'u da viska de",
	"da ro de zo'u da viska de",
	// 16.4
	"da zo'u da viska la djim",
	"da poi prenu zo'u da viska la djim",
	"ro da zo'u da vasxu",
	"ro da poi gerku zo'u da vasxu",
	"da poi gerku zo'u da vasxu",
	// 16.5
	"da viska mi",
	"ro da poi gerku cu vasxu",
	"ro da poi prenu ku'o de poi gerku ku'o zo'u de batci da",
	"de poi gerku cu batci ro da poi prenu",
	"ro da poi prenu cu se batci de poi gerku",
	"di poi prenu zo'u ti xarci di di",
	"ti xarci di poi prenu ku'o di",
	// 16.6
	"su'o da zo'u da viska mi",
	"re da zo'u da viska mi",
	"su'oreda zo'u da viska mi",
	"re da viska mi",
	"su'ore da viska mi",
	"re prenu cu viska mi",
	"re da poi prenu cu viska mi",
	"re da poi prenu zo'u da viska mi",
	// 16.7
	"ci gerku cu batci re nanmu",
	"ci da poi gerku cu batci re de poi nanmu",
	"ci da poi gerku ku'o re de poi nanmu zo'u da batci de",
	"re de poi nanmu ku'o ci da poi gerku zo'u da batci de",
	"ci gerku ce'e re nanmu cu batci",
	"nu'i ci gerku re nanmu cu batci",
	"nu'i ci gerku re nanmu nu'u cu batci",
	"le ci gerku cu batci le re nanmu",
	"ro le ci gerku cu batci le re nanmu",
	"le ci gerku cu batci ro le re nanmu",
	"ro le ci gerku cu batci ro le re nanmu",
	// 16.8
	"ro da poi klama le zarci cu cadzu le foldi",
	"ro da zo'u da go klama le zarci gi cadzu le foldi",
	"mi nitcu da poi tanxe gi'e bramau ti",
	"da poi tanxe gi'e bramau ti zo'u mi nitcu da",
	"mi nitcu lonu mi ponse lo tanxe poi bramau ti",
	"mi nitcu lonu da zo'u da se ponse mi gi'e tanxe gi'e bramau ti",
	"da poi tanxe gi'e bramau ti zo'u mi nitcu lenu mi ponse da",
	// 16.9
	"mi na klama le zarci",
	"naku zo'u mi klama le zarci",
	"naku de zo'u de zutse",
	"su'ode naku zo'u de zutse",
	"roda su'ode zo'u da prami de",
	"su'ode roda zo'u da prami de",
	"naku roda su'ode zo'u da prami de",
	"naku su'ode roda zo'u da prami de",
	"su'oda naku su'ode zo'u da prami de",
	"rode naku roda zo'u da prami de",
	"su'oda rode naku zo'u da prami de",
	"rode su'oda naku zo'u da prami de",
	"noda rode zo'u da prami de",
	"naku noda rode zo'u da prami de",
	"naku naku su'oda rode zo'u da prami de",
	"su'oda rode zo'u da prami de",
	// 16.10
	"mi e do klama ri",
	"mi klama ti .ije do klama ti",
	"mi enai do prami roda",
	"mi prami roda .ijenai do prami roda",
	"roda zo'u mi prami da .ije naku do prami da",
	// `zo'u` removed
	"su'oda zo'u mi prami da .ije naku do prami da",
	// 16.11
	"su'oda poi verba na klama su'ode poi ckule",
	"naku zo'u su'oda poi verba cu klama su'ode poi ckule",
	"su'oda poi verba ku'o naku klama su'ode poi ckule",
	"su'oda poi verba cu klama rode poi ckule ku'o naku",
	"su'oda poi verba cu klama naku su'ode poi ckule",
	"naku roda poi verba cu klama su'ode poi ckule",
	"su'ode poi ckule ku'o naku se klama rode poi verba",
	"su'o verba naku klama su'o ckule",
	"su'oda poi verba ku'o naku su'ode poi ckule zo'u da klama de",
	"naku roda poi verba ku'o su'ode poi ckule zo'u da klama de",
	"naku zo'u roda poi verba cu klama su'ode poi ckule",
	"ro verba cu na klama su'o ckule",
	"roda poi verba ku'o su'ode poi ckule zo'u de na se klama da",
	"mi naku naku le zarci cu klama",
	// 16.12
	"la djan na klama ga la paris gi la rom",
	"naku zo'u la djan klama ga la paris gi la rom",
	"ge la djan la paris na klama gi la djan la rom na klama",
	"la djein le zarci na ge dzukla gi bajrykla",
	"la djein le zarci ganai dzukla ginai bajrykla",
	"naku zo'u la djein le zarci ge dzukla gi bajrykla",
	"ga la djein le zarci na dzukla gi la djein le zarci na bajrykla",
	"ganai la djein le zarci cu dzukla ginai la djein le zarci cu bajrykla",
	"ga la paris gi la rom naku se klama la djan",
	"la djan naku klama ge la paris gi la rom",
	// 16.13
	"su'o bu'a zo'u la djim bu'a la djan",
	"la djim bu'a la djan",
	"ro bu'a zo'u la djim bu'a la djan",
	// 16.14
	"ci da poi mlatu cu blabi .ije re da cu barda",
	"ci da poi prenu cu se ralju pa da",
	// 17.1
	// (no lojban examples)
	// 17.2
	"ty abu ny ry ubu",
	"ky obu y'y abu",
	"mi cy claxu",
	"micyclaxu",
	// 17.3
	"la iVAN",
	"ibu ga'e vy abu ny to'a",
	"tau sy",
	"tau sy ibu",
	// 17.4
	"zo bu",
	// 17.5
	"y'ybu",
	"kybu",
	"vybu",
	"kybu ubu abu cy ky",
	"tybu",
	"dybu",
	"zai devangar bu",
	"zai katakan bu",
	"zai xiragan bu",
	"ce'a xelveticas bu",
	"ce'a xancisk bu",
	"ce'a pavrel bu",
	// 17.6
	"tei ebu akut bu foi ty tei akut bu ebu foi",
	// 17.7
	// (no examples)
	// 17.8
	"y'ybu abu ny vo zy ibu vo",
	"my ibu ty ty sy ubu by ibu sy y'ybu ibu",
	// 17.9
	"abu prami by",
	"le gerku goi gy cu xekri .i gy klama le zdani",
	"le gerku cu xekri .i gy klama le zdani",
	// corrected to remove glide
	"la stivn mark djonz cu merko .i la aleksandr pavlovitc kuzniietsof cu rusko .i symydy tavla abupyky bau la lojban",
	"abu dunda by cy",
	"abu dunda by boi cy",
	"abu boi dunda by boi cy",
	"abu dunda by boi cy boi",
	"abu boi dunda by boi cy boi",
	"xy boi ro prenu cu prami",
	"xy boi ro boi prenu cu prami",
	// 17.10
	"abu lerfu",
	"abu cu lerfu",
	"me'o abu lerfu",
	"me'o abu cu lerfu",
	"dei vasru vo lerfu po'u me'o ebu",
	"lu abu li'u cu lerfu",
	"la'e lu abu li'u cu lerfu",
	// 17.11
	"li abu du li by su'i cy",
	"li ybu du li ma'o fy boi xy",
	"le vi ratcu cu nymoi le'i mi ratcu",
	"nymai",
	"xyxiky",
	"vei ny lo prenu",
	"vei ny ve'o lo prenu",
	// 17.12
	"la dyny'abub .i la ny'abuty'obub .i la cy'ibu'abub .i la sykybulyl .i la ibubymym .i la ny'ybucyc",
	"la dyny'am .i la ny'aty'om .i la cy'i'am .i la sykybulym .i la ibymym .i la ny'ybucym",
	"la dynyzaz .i la nyzatyzoz .i la cyzizaz .i la sykybulyz .i la ibymyz .i la nyzybucyz",
	"la me dy ny abu",
	"la cribe cu ciska",
	// 17.13
	"me'o se'e cixa cu lerfu la asycy'i'is loi rupnu be fi le merko",
	"me'o se'e rexarerei sinxa le ka panpi",
	// 18.1
	// (no lojban examples)
	// 18.2
	"pa re ci",
	"pa no",
	"pa re ci vo mu xa ze bi so no",
	// 18.3
	"ni'u pa",
	"ci pi pa vo pa mu",
	"re fi'u ze",
	"fi'u ze",
	"pi ci mu ra'e pa vo re bi mu ze",
	"ci mu ce'i",
	"pa ki'o re ci vo ki'o mu xa ze",
	"pa ki'o re ci ki'o vo",
	"pi ki'o re re",
	"pi pa ki'o pa re ki'o pa",
	// 18.4
	"ma'u ci'i",
	"ci ka'o re",
	"ci'i no",
	"pai",
	"te'o",
	"pa pi re pi ci",
	"pa ni'u re",
	// 18.5
	"li pa su'i pa du li re",
	"le ci prenu",
	"levi sfani cu grake li ci",
	"li ci prenu",
	"li ma'u pa su'i ni'u pa du li no",
	"li mu su'i pa du li ci su'i ci",
	"li ci su'i vo pi'i mu du li reci",
	"li ci su'i vo pi'i mu du li cimu",
	"li ci su'i vo bi'e pi'i mu du li reci",
	"li vei ny su'i pa ve'o pi'i vei ny su'i pa du li ny te'a re su'i re bi'e pi'i ny su'i pa",
	"li vei ny su'i pa ve'o pi'i vei ny su'i pa ve'o du li ny te'a re su'i re bi'e pi'i ny su'i pa",
	"li vei ny su'i pa ve'o pi'i vei ny su'i pa du li ny bi'e te'a re su'i re bi'e pi'i ny su'i pa",
	"li vei ny su'i pa ve'o pi'i vei ny su'i pa ve'o du li ny bi'e te'a re su'i re bi'e pi'i ny su'i pa",
	// 18.6
	"li su'i paboi reboi ci du li xa",
	"li su'i paboi reboi ciboi du li xa",
	"li py su'i va'a ny ku'e su'i zy du li xy",
	"li zy du li ma'o fyboi xy",
	"li pe'o su'i paboi reboi ciboi ku'e du li xa",
	"li py su'i pe'o va'a ny ku'e su'i zy du li xy",
	"li zy du li pe'o ma'o fyboi xy ku'e",
	// 18.7
	"li xy mleca li mu",
	"py du xyboi zy",
	"li re su'i re na du li mu",
	// 18.8
	"mi catlu pa prenu",
	"mi catlu ro prenu",
	"mi catlu so'a prenu",
	"mi catlu so'e prenu",
	"mi catlu so'i prenu",
	"mi catlu so'o prenu",
	"mi catlu so'u prenu",
	"mi citka piro lei nanba",
	"mi catlu no'o prenu",
	"mi citka pino'o lei nanba",
	"mi catlu da'a re prenu",
	"mi catlu da'a so'u prenu",
	"ro ratcu ka'e citka da'a ratcu",
	"li ci vu'u re du li ma'u",
	"li ci vu'u vo du li ni'u",
	"mi ponse le rupnu be li ma'u",
	"mi ponse le rupnu be li rau",
	"mi viska le rore gerku",
	"mi speni so'ici prenu",
	// 18.9
	"ji'i vo no",
	"vo no ji'i mu no",
	"re pi ze re ji'i",
	"re pi ze re ji'i ma'u",
	"re pi ze pa ji'i ni'u",
	"mi catlu su'e re prenu",
	"mi catlu su'o re prenu",
	"mi catlu me'i re prenu",
	"mi catlu za'u re prenu",
	"mi catlu su'o prenu",
	// 18.10
	"li panopano ju'u re du li pano",
	"li daufeigai ju'u paxa du li rezevobi",
	"li jaureivai ju'u paxa du li cimuxaze",
	"li vai pi bi ju'u paxa du li pamu pi mu",
	"ci pi'e re re pi'e vono",
	"li ci pi'e re re pi'e vono su'i pi'e ci pi'e cici du li ci pi'e rexa pi'e paci",
	"li pa pi'e re pi'e ci ju'u reno du li vovoci",
	// `li` added
	"li pano ju'u reno",
	// `li` added
	"li pa pi'e no ju'u reno",
	"li pa pi'e vo pi ze ju'u reno du li revo pi cimu",
	"dei jufra panopi'epapamoi",
	// 18.11
	"lei mi ratcu cu cimei",
	"mi poi pamei cu cusku dei",
	"lei ratcu poi zvati le panka cu so'umei fo lo'i ratcu",
	"le'i ratcu poi zvati le panka cu se so'imei",
	"ti pamoi le'i mi ratcu",
	"ta romoi le'i mi ratcu",
	"mi raumoi le velskina porsi",
	"levi sanmi cu fi'ucisi'e lei mi djedi cidja",
	"le nu lo sicni cu sedja'o cu pimucu'o",
	"levi rozgu cu sofi'upanova'e xunre",
	"lei ratcu poi zvati le panka cu du'emei fo mi",
	"ta nymoi le'i mi ratcu",
	"ta me li ny su'i pa me'u moi le'i mi ratcu",
	"le nu mi nolraitru cu me le'e snime bolci be vi la xel cu'o",
	// 18.12
	"li re su'i re du li xo",
	"le xomoi prenu cu darxi do",
	"li remu pi'i xa du li paxono",
	// 18.13
	"li xyboixici du li xyboixipa su'i xyboixire",
	"xyboixino",
	"xyboixiny",
	"xyboixiveinysu'ipa",
	"xyboixiveinysu'ipave'o",
	"xyboi xi byboi xivo",
	// 18.14
	"li tu'o va'a ny du li no vu'u ny",
	"li cinonoki'oki'o du li bi gei ci",
	// `li` added
	"li gei reno",
	// `li` added
	"li papano bi'eju'u re gei pipanopano bi'eju'u re ge'a re",
	// 18.15
	"li jo'i paboi reboi te'u su'i jo'i ciboi voboi du li jo'i voboi xaboi",
	// `li` added
	"li jo'i biboi paboi xa pi'a jo'i ciboi muboi ze ge'a jo'i voboi soboi re",
	// `li` added
	"li jo'i biboi ciboi vo sa'i jo'i paboi muboi so ge'a jo'i xaboi zeboi re",
	// 18.16
	"li fu'a reboi ci su'i du li mu",
	"li fu'a reboi ci pi'i voboi mu pi'i su'i du li rexa",
	"li fu'a ciboi muboi vu'u du li fu'a reboi tu'o va'a",
	"li cinoki'oki'o du li fu'a biboi ciboi panoboi ge'a gei",
	// 18.17
	// duplicate: "vei ci a vo ve'o prenu cu klama le zarci",
	// duplicate: "vei ga ci gi vo ve'o prenu cu klama le zarci",
	"li re su'i re du li vo lo'o onai lo nalseldjuno namcu",
	// duplicate: "li re su'i je pi'i re du li vo",
	// corrected from gek to guhek, also duplicate
	// duplicate: "li re gu'e su'i gi pi'i re du li vo",
	"go li abu bi'epi'i vei xy te'a re ve'o su'i by bi'epi'i xy su'i cy du li no gi li xy du li vei va'a by ku'e su'i ja vu'u fe'a vei by bi'ete'a re vu'u vo bi'epi'i abu bi'epi'i cy ve'o ve'o fe'i re bi'epi'i abu",
	"go li abu bi'epi'i vei xy te'a re ve'o su'i by bi'epi'i xy su'i cy du li no gi li xy du li vei va'a by ku'e su'i ja vu'u fe'a vei by bi'ete'a re vu'u vo bi'epi'i abu bi'epi'i cy ve'o ku'e ve'o fe'i re bi'epi'i abu",
	"li no ga'o bi'o ke'i pa",
	"li pimu su'i ni'upimu bi'o ma'upimu",
	"xy xi vei by ce'o dy",
	"xy xi vei by ce'o dy ve'o",
	// 18.18
	"li na'u tanjo te'u vei pai fe'i re du li ci'i",
	"li na'u tanjo te'u vei pai fe'i re ve'o du li ci'i",
	"li ni'e ni clani pi'i ni'e ni ganra pi'i ni'e ni condi te'u du li ni'e ni canlu",
	"li ni'e ni clani te'u pi'i ni'e ni ganra te'u pi'i ni'e ni condi te'u du li ni'e ni canlu",
	"li mo'e re ratcu su'i mo'e re ractu du li mo'e vo danlu",
	"mi viska vei mo'e lo'e lanzu ve'o cinfo",
	// 18.19
	"li re su'i re du li vo",
	"me'o re su'i re du me'o vo",
	"li ni'umu cu nu'a va'a li ma'umu",
	"li re na'u mo re du li vo",
	"nu'a su'i",
	"li re na'u nu'a su'i re du li vo",
	"pamai",
	"remai",
	"romai",
	// duplicate: "nymai",
	"pasomo'o",
	// 18.20
	// (no examples)
	// 18.21
	"li ci se vu'u vo du li pa",
	"li ci na'e su'i vo du li pare",
	"li ci to'e vu'u re du li mu",
	"li re su'i re du li na'ebo mu",
	"la zel poi gunta la tebes pu nanmu",
	"la zemei poi gunta la tebes pu nanmu",
	// 18.22
	"li bize",
	"li vo pi'i reno su'i ze",
	"li mo'e voboi renomei te'u su'i ze",
	"li vo pi'e ze ju'u reno",
	// 19.1
	// (no examples)
	// 19.2
	"mi klama le zarci .i do cadzu le bisli",
	// 19.3
	// created
	"ni'o mi klama no'i do klama da'o",
	// 19.4
	// duplicate: "mi klama le zarci",
	"le nuzba zo'u mi co'i facki",
	"mi co'i facki le nuzba",
	"le finpe zo'u citka",
	"ro da poi prenu ku'o su'o de zo'u de patfu da",
	"loi patfu ro da poi prenu ku'o su'o de zo'u de patfu da",
	"loi jdini zo'u tu'e do ponse .inaja do djica",
	"loi jdini zo'u tu'e do ponse .inaja do djica tu'u",
	"do ponse loi jdini .i naja do djica ri",
	"do ponse loi jdini .inaja do djica tu'a ri",
	// 19.5
	"xu do klama le zarci",
	"ma klama le zarci",
	// duplicate: "do klama ma",
	// duplicate: "le zarci",
	"ma klama ma",
	"mi le zarci",
	"ma fa'u ma klama ma fa'u ma",
	"la djan la marcas le sarci le briju",
	"la lojban mo",
	"do viska xo prenu",
	"vomu",
	// 19.6
	"mi cu klama le zarci le zdani le dargu le karce",
	"le karce cu xe klama le zarci le zdani le dargu mi",
	"fo le dargu fi le zdani fa mi fe le zarci fu le karce cu klama",
	"la'edi'u cu nunkla mi le zarci le zdani le dargu le karce",
	"le karce cu sexixa nunkla mi le zarci le zdani le dargu la'edi'u",
	"fu le dargu fo le zdani fe mi fa la'edi'u fi le zarci faxixa le karce cu nunkla",
	"da xi vo",
	"ko'i xi paso",
	"li xyboixipa du li xyboixire su'i xyboixici",
	"la djan xipa cusku lu mi'enai do li'u la djan xire",
	"li pimu jei mi ganra",
	"mi ja'a xipimu ganra",
	// 19.7
	"mi klama pamai le zarci .e remai le zdani",
	// 19.8
	"mi viska le blanu ia zdani",
	"mi viska le blanu ia zdani ku",
	"mi viska le blanu zdani ia",
	"mi viska le blanu zdani ia ku",
	"mi viska le ia blanu zdani",
	"mi viska le ia blanu zdani ku",
	"mi viska le blanu zdani ku ia",
	"ia mi viska le blanu zdani",
	"i ia mi viska le blanu zdani",
	"mi viska le fu'e ia blanu zdani fu'o ponse",
	// 19.9
	"mi pu cusku lu mi'e djan",
	"mi pu cusku lu mi'e djan li'u",
	"lo'u mi du do du la djan le'u na tergerna la lojban",
	"lu le mlatu cu viska le finpe li'u zo'u lo'u viska le le'u cu selbasti ei lo'u viska lo le'u",
	"la tcarlis cusku lu le ninmu cu morsi li'u .iku'i ri jmive",
	"la tcarlis cusku lo'u le ninmu cu morsi le'u .iku'i ri jmive",
	// 19.10
	"zo si lojbo valsi",
	"zoi gy John is a man gy cu glico jufra",
	"zoi gy John is a man gy glico jufra",
	// ungrammatical: "mi djuno fi le valsi po'u zoi gy gyrations gy",
	"mi djuno fi le valsi po'u zoi jai gyrations jai",
	"zoi ry sku ry cu rafsi zo cusku",
	"zoi ry sku ry rafsi zo cusku",
	"zo bab cmene la bab",
	"zo bab cmene la'e zo bab",
	"lu'e la bab cmene la bab",
	"la bab cmene la bab",
	"la'o dy Goethe dy cu me la'o ly Homo sapiens ly",
	// 19.11
	"mi viska la ba'e djordj",
	"mi viska ba'e la djordj",
	"ba'e mi viska la djordj",
	"mi ba'e viska la djordj",
	// corrected to remove glides
	"mi klama la za'e albeiniias",
	// 19.12
	"doi lisas mi djica le nu to doi frank ko sisti toi do viska le mlatu",
	"la frank cusku lu mi prami do to'i sa'a do du la djein toi li'u",
	"la frank prami sei la frank gleki la djein",
	"la frank prami sei gleki la djein",
	"la frank prami sei gleki be fa la suzn la djein",
	"la djan cusku lu mi klama le zarci li'u",
	"lu mi klama le zarci seisa'a la djan cusku be dei li'u",
	"lu seisa'a la djan cusku be dei mi klama le zarci",
	"lu mi klama seisa'a la djan cusku le zarci",
	// 19.13
	// todo erasure
	/*
	"ti gerku si mlatu",
	"ta blanu zdani si si xekri zdani",
	"zo bab se cmene zo si si si la bab",
	"mi tavla fo la esperanto si si esperanton",
	"mi cusku zoi fy gy fy si si si si zo djan",
	"mi se cmene zo djan si si zo djordj",
	"mi viska le sa .i mi cusku zo djan",
	"mi cusku zo djan",
	"mi viska le blanu zdan sa le xekri zdani",
	*/
	// 19.14
	"y",
	// 19.15
	"fa'o",
	// 21.1
	"ni'o la berti brife jo'u la solri .i la berti brife jo'u la solri pu troci leka djuno ledu'u makau traji leka vlipa vau fo le'i me lenei .icabo le pa litru noi dasni lo glare kosta cu mo'u klama .i lu'i le remei pu simxu leka tugni fi lenu traji leka vlipa fa le traji be leka clira fa lonu ce'u snada leka gasnu lenu le pa litru co'u dasni le kosta .i baku la berti brife co'a traji cupra le brife .i ku'i lonu by.by. zenba leka cupra le xokau brife cu rinka lonu le pa litru cu zukte leka zenba leka sela'u li xokau se tagji le kosta .ibazabo la berti brife co'u troci .i baku la solri co'a dirce lo milxe glare .ibazibo le pa litru co'u dasni le kosta .iseki'ubo la berti brife co'a bilga tugni fi lonu la solri cu traji leka vlipa vau fo la berti brife ce la solri",
];
