[package]
edition = "2021"
name = "macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }

[features]
make-assert-parse-test = []
